### ISSUE TITLE
Gallery Markup Prototype

### ISSUE THREAD

**Issue by ebollens** [ucla-oarc-web/WebBlocks#10]

**Comment by ebollens** [comment]
What would you think about putting this in a new section like `ui/gallery` or `widget/gallery`? I don't think `entity` is a good base area for this, while right now it's not in any area at all.

**Comment by alicetseng** [comment]
Sure I think ui would work for the macro components -- which is what we'll mostly be having since bootstrap already covers many of the discreet entities. I'll take care of that.

**Comment by ebollens** [comment]
Empty page on wiki spun for this:
https://github.com/ucla/WebBlocks/wiki/Gallery

**Comment by alicetseng** [comment]
Great - thanks. @ebollens - noticed that gallery was one of the items in the interactive component family and I'm seeing 2 types of components called "gallery" common on the web: interactive vs. data-collections. Can you give a read over these notes and give your thoughts? https://github.com/ucla/WebBlocks/wiki/Gallery.

Bit of aside but tangentially related - twitter bootstrap library has many overlapping items (nav bar, hero unit, thumbnails, buttons, lists, etc.) -- if we're adopting bootstrap -- should we be prototyping just elements that aren't included and where they already exist just extend for UCLA branding needs (a.k.a. doing extensions)? 

In bootstrap what they call "thumbnails" is essentially what the gateway template is calling a "gallery" and what YUI calls a "display collection" ... which pattern are we adopting? Should we just follow bootstrap and rename this component ui/gallery a thumbnail, instead? And in that case just extend it to include more images at a smaller size?

**Comment by ebollens** [comment]
@atsengucla my vote is for `interactivity/player/gallery` and `entity/list/gallery`. The logic behind my reasons can be found on the wiki page. If we're in agreement, want to update the component list and deprecated the discussion page for ui/gallery, which isn't a component now.

As for overlapping items, my thought is that we should define ALL of the elements we see as being useful (all the way down to buttons). Then we figure out if there's a Bootstrap class that we can extend to simplify our work. The reason I say this is we don't want to just say that Bootstrap did it right, but rather figure out what we think is actually right and then meld Bootstrap into it if possible.

I'll use your thumbnails versus gallery nomenclature as an example. I disagree with Bootstrap that a thumbnail has any sort of presentational meaning beyond it in exclusivity. A list of thumbnails to me does not say a grid layout. It might as easily be a vertically-oriented list with thumbnails. Instead, the gridded list is a gallery, whereas the styling around an individual image is a thumbnail. At least that's my perspective on it. From that, I'd then say that we define a gallery, but that we extend the Bootstrap `thumbnails` class to do it - and similarly we also allow you to just use a `thumbnail` in exclusivity from the gallery.

**Comment by ebollens** [comment]
Oh, one other thing you bring up: modifying Bootstrap or extending and then modifying our extensions.

Personally, my thought is that we tweak the existing class as far as its reasonable to do in terms of appearance (but not changing its markup semantics), then extend it, and finally add additional semantics to ours if need be. This would mean for something like `.navbar` to `nav.bar`, we might do something like:
1. Modify decorative properties in `.navbar` (though of course in our own precompiler sheets not Bootstrap's itself)
2. Extend `.navbar` into `nav.bar`
3. Add additional semantics like support for `aside`

**Comment by alicetseng** [comment]
OK. Does anyone else have thoughts on this? @modernrockstar? let me know if we're missing anything. Otherwise, I'll take care of the changes and move the associated files over tomorrow.

**Comment by alicetseng** [comment]
I've been reading up some more and have added extra notes. I'm thinking figure is a strong candidate for both types of galleries. See new notes here: https://github.com/ucla/WebBlocks/wiki/Gallery

**Comment by ebollens** [comment]
`entity/figure/gallery` is my vote then.

**Comment by alicetseng** [comment]
Updated prototype and wiki pages to reflect new options for gallery div\figure.

**Comment by alicetseng** [comment]
Updating links in comments to provide better trail.

**Comment by alicetseng** [comment]
@ebollens @loganfranken @modernrockstar (anyone else) please give this entity a once over. I've updated the prototype, readme and wiki. If no problems/issues can be found, I'd like to push this to pending dev.

**Comment by loganfranken** [comment]
@atsengucla Everything looks good to me! I had one small suggestion: what do you think about combining the two forms since you could make the argument that the second form would semantically be a _list_ of `figure` elements, so the prototype would support both:

``` html
<!-- 1..* -->
<li>
    <!-- 1 -->
    <a href="{Image 1 URL}">
        <img src="{Image 1 Thumbnail URL}" alt="{Image 1 Alt Text}" />
    </a>
</li>
```

As well as:

``` html
<!-- 1..* -->
<li>
    <!-- 1 -->
    <figure>
        <!-- 1 -->
        <a href="{Image 1 URL}">
            <img src="{Image 1 Thumbnail URL}" alt="{Image 1 Alt Text}" />
        </a>
        <!-- 0..1 -->
        <figcaption>Caption for the Item Here</figcaption>
    </figure>
</li>
```

In other words: the same basic markup except we have added a parent `figure` element and a sibling `figcaption` element (but kept the list, is my main point).

**Comment by alicetseng** [comment]
@loganfranken - I like this idea; I'll update the prototype this afternoon/evening. thanks for the suggestion.

**Comment by loganfranken** [comment]
Per our meeting today: this all looks good to me. I think we can move this forward to implementation.

**Comment by alicetseng** [comment]
This design issue is closed; ready for implementation.

**Comment by loganfranken** [comment]
Created implementation issue: #86
