### ISSUE TITLE
Entity/Button

### ISSUE THREAD

**Issue by loganfranken** [ucla-oarc-web/WebBlocks#100]
Development task for `entity/button` (prototype issue: #72)

**Comment by ebollens** [comment]
Reassigning this one from @loganfranken to myself because I'm going to use it as a test case for color strategy.

**Comment by ebollens** [comment]
Mood-based backgrounds on buttons are now pretty much implemented with the exception that the Bootstrap adapter does not let you change the border color of the buttons given a CSS ordering issue. If we added an !important flag, we could overcome this, but that's not proper CSS convention, so I'll have to look more at this later. Creating a different issue for this.

**Comment by ebollens** [comment]
Buttons are working for mood and branding colors, so closing this issue.

**Comment by ebollens** [comment]
Reopening this as I missed the size controls. There's also a disabled control, but I'm going to leave that one alone for the moment.
