### ISSUE TITLE
"can't convert Pathname to String" Error

### ISSUE THREAD

**Issue by loganfranken** [ucla-oarc-web/WebBlocks#101]
When trying to run `rake`, I was getting the following error: `can't convert Pathname to String`

I was able to fix it by changing the following line of code:
https://github.com/ucla/WebBlocks/blob/master/rake/build/blocks.rb#L308

From:

``` ruby
@modules.push mod.sub /^#{Regexp.escape(dir_src_core_definitions)}\//, ''
```

To:

``` ruby
@modules.push mod.sub /^#{Regexp.escape(dir_src_core_definitions.to_s)}\//, ''
```

Based on advice from this forum post:
http://blog.nikosd.com/2011/11/fix-ruby-19-cant-convert-pathname-to.html

But I don't know enough about Ruby (really, anything about Ruby) to determine if that's a viable fix or not.

**Comment by ebollens** [comment]
Makes sense, but I think the `to_s` call is in the wrong place.

The ultimate problem is that `WebBlocks::Util.dir_from_dir_stack_array` is returning a Pathname object in its recursive loop when in reality it should return a string (which would obsolete this issue completely). I'm going to see if making this change is a reasonable fix.

**Comment by ebollens** [comment]
@loganfranken please check out 542167b and let me know if that resolves your problem.

**Comment by loganfranken** [comment]
@ebollens Yup, appears to be working. Thanks!

**Comment by ebollens** [comment]
Awesome, closing this then.
