### ISSUE TITLE
Alternative List Style Type Shortcuts

### ISSUE THREAD

**Issue by loganfranken** [ucla-oarc-web/WebBlocks#112]
Foundation provides some shortcuts for triggering some of the alternative `list-style-type` values for lists (http://foundation.zurb.com/docs/typography.php).

I'm not really a fan of the list types they chose, but I _do_ like the idea of maybe providing a shortcut for activating the `upper-roman` and `lower-roman` types:
http://jsfiddle.net/ksfpg/

Here's the full list of types:
https://developer.mozilla.org/en-US/docs/CSS/list-style-type

Thoughts?

**Comment by loganfranken** [comment]
I implemented this to include `lower-roman`, `upper-roman`, `upper-alpha`, and `lower-alpha`. I'm still debating this with myself, but I feel that whether or not a list is using alpha or roman for the item markers is actually a semantic consideration (or at least _very close_ to one) that would be appropriate referenced in the markup.

`disc`, `circle`, and `square` would gross me out as shortcuts, though. I would rather not include them unless someone feels strongly otherwise.

I'm also considering removing `ul` as an option for these shortcuts as it does not make sense for an unordered list to have any of the aforementioned list style types.

**Comment by ebollens** [comment]
I like the Roman and Alpha.

However, another thing we might want to consider is handling `ul` and `ol` outlines where different levels of `ul` and `ol` actually receive different treatments concerning which one they use so you have like I. 1. A. i. or something like that for multiple layers of cascade. Dunno, just an idea.
