### ISSUE TITLE
No Entity Class Name Extension

### ISSUE THREAD

**Issue by loganfranken** [ucla-oarc-web/WebBlocks#115]
I'm not sure if this is too early for this, but I'm working on a project using Web Blocks where I'm starting fresh and I would like to use the entities without the explicit class name (from #98).

There was talk of an extension that would allow for this; I feel like this is something we definitely want in the first release (since someone integrating Web Blocks into an existing project would probably love the `table.table` use case for interoperability, but it could be a bit of a bear for someone starting fresh to add `.table` to a `table` or `.list` to a `list`).

**Comment by ebollens** [comment]
I'm +1 on this and will implement it now for the entities that we've got thus far. Assigning to myself.

**Comment by ebollens** [comment]
I've added the bindings to this in a new `implicit-html` extension.
