### ISSUE TITLE
Entity/Nav/Main Markup Prototype

### ISSUE THREAD

**Issue by ebollens** [ucla-oarc-web/WebBlocks#12]
Joseph and I have discussed that it makes sense to take the `nav` that we're building into `.masthead` as the primary navigation (two-tier submenu) and break it out into a separate `entity/nav/main` with the class `nav.main`.

Here's te email chain that yielded this:

> From: "Maddela, Joseph" jmaddela@support.ucla.edu
> Date: Thu, 12 Jul 2012 08:36:58 -0700
> To: Eric Bollens ebollens@ucla.edu
> Subject: nav prototype for WebBlocks
> 
> Hi Eric,
> 
> Few comments:
> 
> -The topbar entity you have is actually referring to the upper most navigation on the gateway (Prospective students, current students, faculty..etc)
> Did you want me to work on the main navigation prototype instead?
> 
> -The main nav had to deal with two issue:
> 1)Parent nav items that had child items (submenu)
> 2)Parent nav items that directly linked to a page
> 
> .menuLink was assigned to parent nav items with submenus. The others were just directly linked.

.

> From:  "Bollens, Eric" ebollens@ucla.edu
> To: Joseph jmaddela@support.ucla.edu
> Subject: Re: nav prototype for WebBlocks
> 
> Joseph,
> 
> When you say "Did you want me to work on the main navigation prototype instead?", which navigation are you talking about in particular?
> 
> ~ Eric

.

> From: "Maddela, Joseph" jmaddela@support.ucla.edu
> Date: Thu, 12 Jul 2012 08:42:55 -0700
> To: Eric Bollens ebollens@ucla.edu
> Subject: Re: nav prototype for WebBlocks
> 
> I was referring to the main nav (About, academics, Admissions, UCLA in the community…etc)
> 
> The prototype you started was for the 'top bar" which was more of an 'audience nav' which we considered a secondary/utility type nav.
> 
> -joseph

.

> From: "Bollens, Eric" ebollens@ucla.edu
> To: Joseph jmaddela@support.ucla.edu
> Subject: Re: nav prototype for WebBlocks
> 
> Joseph,
> 
> Ah, I see what you're getting at.
> 
> If you look at the prototype.html file for masthead, you'll see a nav after h1 and aside. That's the one that would contain About, Academics, etc. You can see what I mean by looking at the -ex–ucla_gateway.html file. However, this does raise a good point: masthead might actually use a navbar entity template for that entire nav section.
> 
> However, the question would be: how would a primary nav like the one in masthead be different than nav/topbar if you used it outside of masthead? One answer is maybe that we just define it as a base prototype with semantic meaning, but maybe not presentational except for where it's a composite within other regions like the masthead. In that case, you'd have nav > ul > li > a + ul > li > a and maybe we'd even allow a third tier in here. Thoughts?
> 
> ~ Eric

.

> From: "Maddela, Joseph" jmaddela@support.ucla.edu
> Date: Thu, 12 Jul 2012 09:03:48 -0700
> To: Eric Bollens ebollens@ucla.edu
> Subject: Re: nav prototype for WebBlocks
> 
> Cool…making more sense now.
> 
> Quick note about the structure. The current one we're using is: ul > li > a + ul > li > ul > li
> 
> We used ul in the subnav a + ul > li to control the columns in the submenu. We can go with your proposed structure nav > ul > li > a + ul > li > a. Will it still allow us to control the submenu if we wanted to divide them into columns?
> 
> We purposely limited the nav not to have a third tier to keep a consistent design.  Is web blocks going to be a framework that has ties with the gateway design?
> 
> -Joseph

.

> From: <Bollens>, "Bollens, Eric" ebollens@ucla.edu
> To: Joseph jmaddela@support.ucla.edu, "Bollens, Eric" ebollens@ucla.edu
> Subject: Re: nav prototype for WebBlocks
> 
> Joseph,
> 
> I don't think there is a semantic benefit to your markup.
> 
> Consider the meaning of ul > li a + ul > li > ul. This states you have a list with a list of lists. However, what you're talking about here is just a list of lists. That's why I propose ul > li a + ul + ul instead. Semantically, I've rarely, if ever, seen a list used to handle a column layout – we usually use divs for that or else drive it contextually based on sibling order. The only exception would be if your columns were actually semantically differing sublists. However, that's not how it appears here.
> 
> However, this leads us to another question: should you be defining your columns or letting the framework responsively pick how many columns are used? When I look at the Gateway, your columns have no semantic difference. When I shrink the masthead to a certain size (say tablet size), it might make sense to shift the layout to use two columns rather than three. Using multiple lists or lists of lists for this submenu, you can't do this (best you could do is cascade the third column below the first two). It also doesn't consider the case where four columns might be reasonable (huge screens). That was my initial reason for saying we should use a single list instead and let the framework figure it out.
> 
> Thoughts on that?
> 
> ~ Eric

.

> From: "Maddela, Joseph" jmaddela@support.ucla.edu
> Date: Thu, 12 Jul 2012 09:25:32 -0700
> To: Eric Bollens ebollens@ucla.edu
> Subject: Re: nav prototype for WebBlocks
> 
> Eric,
> I agree the framework should figure out the column count, or at least have the user define the max column count and calculate everything else automatically, like dividing the list evenly between X amount of columns.
> 
> I'll submit a prototype. Do you want me to name it mainNav?

This shall be the issue related to `nav.main`.

**Comment by ebollens** [comment]
Spun out a subpage in the wiki for this when we've got it defined:
https://github.com/ucla/WebBlocks/wiki/Entity-Nav-Main

**Comment by ebollens** [comment]
Joseph, just FYI, copied the prototype out of `entity/header/masthead` and put it in `entity/nav/main` in 68ce987. Tweak as you see fit. 

One thing I'm thinking (see issue #3 for a discussion on it) is about whether it makes sense to require the user to put an `a.close` element for sublists or whether we want to add a `.closeable` class to the `nav.main` entity itself that auto-inserts them (responsively based on viewport). Thinking about it, we can probably provide both in fact, but just something to keep in mind too.

**Comment by modernrockstar** [comment]
Sorry for the late reply. Been out sick with the flu.Eric, i think it makes sense to let the framework decide whether to place a close button. All this time we've assumed that main nav will always be at the top. How do we deal with templates that don't use a top nav as their 'main nav' but instead use a side nav?-joseph

-------- Original Message --------
Subject: Re: [WebBlocks] Gateway Main Nav Markup Prototype (#12)
From: Eric Bollens
reply@reply.github.com
Date: Thu, July 12, 2012 10:41 am
To: Joseph Maddela joe@modernrockstar.com
Joseph, just FYI, copied the prototype out of `entity/header/masthead` and put it in `entity/nav/main` in 68ce987. Tweak as you see fit. 

## One thing I'm thinking (see issue #3 for a discussion on it) is about whether it makes sense to require the user to put an `a.close` element for sublists or whether we want to add a `.closeable` class to the `nav.main` entity itself that auto-inserts them (responsively based on viewport). Thinking about it, we can probably provide both in fact, but just something to keep in mind too.

**Comment by ebollens** [comment]
@modernrockstar @atsengucla what do you think of borrowing from Bootstrap's use of concepts on this one where a "bar" is horizontal and a "list" is vertical? This would mean that `nav.bar` is a horizontal bar across the page (and maybe we use `.top` to fix it to the top in an fixed context). We could then have `nav.list` which creates a vertical bar. We probably shouldn't get into a discussion of vertical nav bars in this thread though because there's a lot of thinking to be done with things like the width of such a bar (if we want to talk about this, let's spin off a second topic).

If we're happy with the logic above, then I think we should go ahead and call this a defined entity and then I can start working on implementation (now that #5 and #16 are coming along well).

**Comment by alicetseng** [comment]
@ebollens - what you're proposing sounds logical to me. I'm for bar = horizontal and list= vertical. I'm in the thick of some Plone Diazo templates but have carved out time tonight and this weekend to catch up on the other entities. more later.

**Comment by modernrockstar** [comment]
I like the list and bar options as well.

**Comment by ebollens** [comment]
@atsengucla no worries, I'll be out until next Wednesday.

**Comment by ebollens** [comment]
Currently, we have the following for this:
- `-ex-ucla_gateway.html`
- `prototype.html`

See https://github.com/ucla/WebBlocks/wiki/Creating-an-Entity-Prototype for remaining things to do:
- `README.md`
- `-ex-img-ucla-gateway.png`

I'm going to go ahead and rename `-ex-ucla_gateway.html` to `-ex-ucla-gateway.html` and I've created a development task to produce the entity template in SASS for this in #30.

**Comment by ebollens** [comment]
Closing this as a lingering ticket as it's already on to implementation by @loganfranken in #30.
