### ISSUE TITLE
Error Text?

### ISSUE THREAD

**Issue by ebollens** [ucla-oarc-web/WebBlocks#153]
Right now, our color strategy (https://github.com/ucla/WebBlocks/wiki/Color-Strategy) seems to be missing one key feature: _error_. The problem, as I see it, is that we already have two moods that are similar: important and danger. However, error is a bit different in context than either of these two. Should we add another mood?

@loganfranken @atsengucla @ccheung

**Comment by alicetseng** [comment]
hey @ebollens is danger a common use-case? I'd think error would be a decent replacement for danger. Maybe rather than adding a new one, just subbing?

**Comment by ebollens** [comment]
@atsengucla the `danger` use case fits for things like a delete button.

**Comment by loganfranken** [comment]
Using `.error` as a CSS class has been a very common pattern in my web development experience and I think `.important` and `.danger` stand on their own, so I would support adding it.

**Comment by ebollens** [comment]
This has been moved to milestone 0.1.06, and I've assigned it to myself for implementation.
