### ISSUE TITLE
Entity/Badge

### ISSUE THREAD

**Issue by loganfranken** [ucla-oarc-web/WebBlocks#166]
Implementation ticket for Entity/Badge

Discussion about this entity (and its name) started in #122

**Comment by loganfranken** [comment]
Moving to next milestone

**Comment by ebollens** [comment]
What's the status of this?

**Comment by loganfranken** [comment]
I haven't started work on this. I'm getting slammed at work; if we want this for 0.1.06 I would suggest taking the task from me (sorry!).
