### ISSUE TITLE
Create Entity Prototyping Checklist

### ISSUE THREAD

**Issue by loganfranken** [ucla-oarc-web/WebBlocks#17]
I think we discussed this at an earlier meeting, but I was hoping to establish a checklist of the required elements for prototyping entities to help people start prototyping and also to determine when a given prototype is "done." Based on the current prototypes, I suggest that each entity should have:
1. An HTML file called containing the HTML template for the entity
2. One or more HTML files containing a real-world HTML example
3. One or more example images (JPEG was mentioned earlier, but I would suggest PNG)

Based on current work, I suggest the following naming conventions:
- `prototype.html`
- `-ex-example_name1.html`
- `-ex-example_name2.html`
- `-ex-img-example_image_name1.png`
- `-ex-img-example_image_name2.png`

The `prototype.html` would use Eric's proposed templating syntax. Is everyone comfortable with that? Along with these elements, I suggest creating both an (1) issue and a (2) wiki article, with the wiki article containing the following:
- **Definition**: Short description of the entity
- **Usages**: How the entity is used
- **Responsive Considerations**: How the look and feel of the entity changes across various viewing environments

Am I missing anything?

Also, I think it might be helpful to keep discussions within issues, rather than on each of the entity's wiki articles, but I'm not sure how everyone else feels about that?

**Comment by alicetseng** [comment]
I think what you're proposing sounds sane and doable. I can edit the
entities I started to follow these conventions.

The only thing I'm not sure about is the extra issues discussion pages --
as we're very organically discussing and negotiating the correct usage and
appropriate syntax for many html5 entities -- it's not going to be the
case where the definitions are easily separated from the discussion.

Could I propose the following?
Allow for the discussions to remain on the entity wiki article and messy.
Keeping it in one place has been helpful to keep the workflow fast and
fluid. When an agreed prototype has come to be resolved, for the sake of
clarity, add a clean definition.txt file to the entity directory?
The definition.txt can contain only definition, usages, responsive
considerations.

It seems wiki is optimal for being in sketch/discussion mode and a
readme.txt more "finalized"?

On 7/23/12 11:17 PM, "Logan Franken"
<reply+i-5795860-469fdebd1a41a5e3f8a17dfc4a37ad070bfa4669-1393130@reply.git
hub.com> wrote:

**Comment by loganfranken** [comment]
That sounds good to me, @atsengucla.

I think your `definition.txt` idea sounds good; since you also mention `readme.txt`, what do you think about just using `README` since Github will automatically display it for us (and we can also use markdown)?

**Comment by alicetseng** [comment]
sure. can you explain, though? github is new to me - is there something different than a readme.txt file just naming convention (all caps one word) or is there a feature I need to use that's different?

**Comment by loganfranken** [comment]
I'm still getting the hang of GitHub myself:

I would suggest creating a `README.md` file at the root of each entity directory. I don't think the uppercase matters, but it's the standard convention (and standards make me oh-so happy). The `md` signifies that it's a markdown file, so we can use the GitHub markdown syntax.

What's cool is that GitHub will display the README file of the current directory below the files in that directory. Here's an example from UCLA MWF:
- https://github.com/ucla/mwf
- https://github.com/ucla/mwf/tree/master/var

You can see that the `/var` directory has its own README that displays directly below. I think this would make it really nice and easy to navigate around the entity directories and check out each one.

I might be tripping over my words a bit here, so here's a few examples of what I'm proposing we create:
-  WebBlocks/template/entity/figure/gallery/README.md
-  WebBlocks/template/entity/header/masthead/README.md

**Comment by loganfranken** [comment]
And a possible template for `README.md`:

```
# Entity Name

## Definition

Definition...

## Usages

* Usage 1
* Usage 2
* Usage 3

## Responsive Considerations

Responsive considerations...
```

Which would display as:

# Entity Name

## Definition

Definition...

## Usages
- Usage 1
- Usage 2
- Usage 3

## Responsive Considerations

Responsive considerations...

**Comment by mtakahashi** [comment]
I'm a little hesitant on the mixed "-" and "_" combinations within the file names (-ex-example_name1.html). Is this a commonly used convention?

My preference would be to use all "-" symbols.

**Comment by alicetseng** [comment]
thanks @loganfranken, both the README.md and the template work for me - sounds good.

**Comment by loganfranken** [comment]
Hey @mtakahashi, I was just working from an existing example. I have no problem with using all "-" symbols (hyphens). In fact, I think it would be easier because I know that, personally, I will probably type it incorrectly if we mix them.

If no one objects, let's go with all hyphens:

`-ex-example-name1.html`

**Comment by mtakahashi** [comment]
I strongly agree that we go with all hyphens.

**Comment by ebollens** [comment]
I'm in complete agreement with all of this.

**Comment by loganfranken** [comment]
Thank you all so much for the awesome input!

I created a Wiki page summarizing this discussion:
https://github.com/ucla/WebBlocks/wiki/Creating-an-Entity-Prototype

And I moved the Entities section from [Components](https://github.com/ucla/WebBlocks/wiki/Components) to its own page (linked from the [Wiki Home](https://github.com/ucla/WebBlocks/wiki)):
https://github.com/ucla/WebBlocks/wiki/Entities

I hope that was alright; if not, let me know and I can move things back to how they were.

**Comment by ebollens** [comment]
Looks great Logan. Thanks :)

**Comment by alicetseng** [comment]
Hey this looks great. Just one question - the html comments referencing multiples - I'm not familiar with the shorthand - can you explain it?

**Comment by ebollens** [comment]
Yeah, it's the syntax used in relational design. Here's a bit of clarification:
- `0` zero exactly
- `0..1` zero or one
- `0..*` zero or more
- `1..*` one or more
- `1` one exactly

**Comment by loganfranken** [comment]
Thanks @ebollens, I added that to the wiki article:
https://github.com/ucla/WebBlocks/wiki/Creating-an-Entity-Prototype
