### ISSUE TITLE
Row Collapse at Different Breakpoints

### ISSUE THREAD

**Issue by ebollens** [ucla-oarc-web/WebBlocks#174]
Consider the following code:

``` html
<div class="row">
    <div class="panel-4">...</div>
    <div class="panel-4">...</div>
    <div class="panel-4">...</div>
</div>
```

As it currently stands, these will appear as three concurrent blocks above `$breakpoint-small`:

```
[--][--][--]
```

Below `$breakpoint-small`, these become full-width elements oriented vertically down the page:

```
[-------]
[-------]
[-------]
```

This works in some cases, but doesn't always make sense.

Suppose, for example, we have an arrangement like this:

``` html
<div class="row">
    <div class="panel-12">...</div>
</div>
<div class="row">
    <div class="panel-6">...</div>
    <div class="panel-6">...</div>
</div>
```

This would be like a featured item and two lesser items. At it currently stands, this will collapse into three vertically-oriented full-width panels for devices under `$breakpoint-small`. However, this collapse might not be intended. For example, the sub-panels might simply be images that can have a `max-width:100%;` applied and thus scale properly, making the realignment not necessary.

An easy solution for the pair of panels might be a new class introduced on the containing row:

``` html
<div class="row no-collapse">
    <div class="panel-6">...</div>
    <div class="panel-6">...</div>
</div>
```

Suppose we have the inverse of this:

``` html
<div class="row">
    <div class="panel-2">...</div>
    <div class="panel-2">...</div>
    <div class="panel-2">...</div>
    <div class="panel-2">...</div>
    <div class="panel-2">...</div>
    <div class="panel-2">...</div>
</div>
```

In this case, the panels might not scale down correctly even to `$breakpoint-medium`. As such, we could introduce another class that signals that the collapse should occur at `$breakpoint-medium` instead:

``` html
<div class="row medium-collapse">
    <div class="panel-2">...</div>
    <div class="panel-2">...</div>
    <div class="panel-2">...</div>
    <div class="panel-2">...</div>
    <div class="panel-2">...</div>
    <div class="panel-2">...</div>
</div>
```

To that end, this could even be done at `$breakpoint-large`:

``` html
<div class="row large-collapse">
    <div class="panel-2">...</div>
    <div class="panel-2">...</div>
    <div class="panel-2">...</div>
    <div class="panel-2">...</div>
    <div class="panel-2">...</div>
    <div class="panel-2">...</div>
</div>
```

A `small-collapse` class would thus be synonymous to no class in addition to `row`.

In order to provide greater flexibility for when content collapses, it might make sense to introduce additional classes like `medium-large-collapse`, `medium-small-collapse`, etc. This sort of approach would provide a lot more flexibility for content providers when there's a need to design content that collapses at different sizes based on the design.

One challenge I see with this sort of a scheme, however, is when you end up with `.row [class*="panel-"] .row [class*="panel"]`. These extra classes would add a lot of power, but at the cost of more complexity depending on the arrangement of these within each other.

Another challenge is that, when you're using an arrangement like the initial motivator (of a `.panel-12` and then two `.panel-6` classes), if you did want them to collapse, when they do collapse, you might want to restyle the sizes of fonts in the three different panels to all be the same (since the collapsed version now makes the three synonymous). This could be achieved in a couple of ways: (1) special entities beyond the panel structure that provide this functionality or (2) a creative use of hide and show classes. I'm inclined to prefer the latter - in either case, we can ignore this consideration for the purpose of this ticket, but it should be considered in a future issue.

As a note, the implementation of these selectors will need to be slick enough to avoid leakage of these `-collapse` classes. This could be made simpler by using `.row-[suffix]` instead of `.row.[size]-collapse`, but this would prevent a single `@extend` from inheriting all of these different qualifiers.

Thoughts?

/CC @loganfranken @lnicks @chris4ucla @jeff1evesque @edsakabu @ccheung @atsengucla

**Comment by ebollens** [comment]
As it currently stands, we're adding 4 KB of bulk just to support `.no-collapse` (and `.small-collapse`), primarily because the panel loop has to be scoped more tightly, meaning that instead of just `panel-1`, `panel-2`, etc., we end up with `selector-set-1 panel-1`, `selector-set-2 panel-1`, `selector-set-1 panel-2`, `selector-set-2 panel-2`, etc. Wondering if I can come up with a better inheritance structure to avoid this bulking.

**Comment by ebollens** [comment]
The ebollens/WebBlocks:base/structure-row-collapse branch now has `.no-collapse`, `.small-collapse`, `.medium-collapse`, and `.large-collapse` support. Playing around with this in the demo (sliding the window around), it strikes me that we need to provide a `.medium-small-collapse` and a `.medium-large-collapse` using two additional breakpoints that lie between the existing ones.

I'm still also open to other semantics ideas (not completely convinced `.[size]-collapse` is the best name if someone can offer an alternative).

Also, as a note, this should be broken into multiple submodules in case someone does not want to use the collapse (as it adds additional bulk - 2KB per breakpoint supported as it currently stands, and I'm doubtful that this can be reduced much).

**Comment by ebollens** [comment]
Cautionary note: #180 and #181 have fixed the way breakpoints work so that `max-width: breakpoint` or `min-width: breakpoint + 1`, so this will need to be applied in the context of this feature as well.

**Comment by ebollens** [comment]
The commit da999e9 resolved the cautionary note above.

@loganfranken @lnicks @chris4ucla @jeff1evesque @edsakabu @ccheung @atsengucla or others: any issues with the implementation as it stands or the semantics I've described?

**Comment by loganfranken** [comment]
Sorry for never getting back to you @ebollens: I think this is fantastic, though!
