### ISSUE TITLE
Additional Structural Semantics

### ISSUE THREAD

**Issue by ebollens** [ucla-oarc-web/WebBlocks#175]
Suppose we have three news items, one that's a highlighted story that spans the full width of the containing element and then two others that are half width and have reduced size.

A full-size mock of this might be something like this:

``` html
<div class="row">
    <div class="panel-12">
        <h1>Featured Item</h1>
        <p>Lorem ipsum...</p>
    </div>
</div>
<div class="row">
    <div class="panel-6 small">
        <h1>Not Featured Item</text-small>
        <p>Lorem ipsum...</p>
    </div>
    <div class="panel-6 text-small">
        <h1>Not Featured Item</h1>
        <p>Lorem ipsum...</p>
    </div>
</div>
```

With a bit of complimenting CSS:

``` css
.text-small {
    font-size: 0.85em;
}
```

However, what happens when this collapses? We get a featured item that has a larger font size than the other two items, although they are now oriented as equals.

We could get around this with visibility classes:

``` html
<div class="row">
    <div class="panel-12">
        <h1>Featured Item</h1>
        <p>Lorem ipsum...</p>
    </div>
</div>
<div class="row">
    <div class="panel-6">
        <div class="text-small hide-small">
            <h1>Not Featured Item</h1>
            <p>Lorem ipsum...</p>
        </div>
        <div class="show-small">
            <h1>Not Featured Item</h1>
            <p>Lorem ipsum...</p>
        </div>
    </div>
    <div class="panel-6">
        <div class="text-small hide-small">
            <h1>Not Featured Item</h1>
            <p>Lorem ipsum...</p>
        </div>
        <div class="show-small">
            <h1>Not Featured Item</h1>
            <p>Lorem ipsum...</p>
        </div>
    </div>
</div>
```

There's a huge catch to this sort of an approach: you have to define multiple cases separately. One of the goals of WebBlocks is to establish semantics that define responsive behavior rather than force a user to have to program for different cases explicitly. As it currently stands, though, we don't have a way to handle this sort of arrangement, which suggests that we need to introduce new semantics.

This is a pretty common arrangement, so we might do something like:

``` html
<div class="[new-class]">
    <div class="[new-subclass] featured">
        <h1>Featured Item</h1>
        <p>Lorem ipsum...</p>
    </div>
    <div class="[new-subclass]">
        <h1>Not Featured Item</text-small>
        <p>Lorem ipsum...</p>
    </div>
    <div class="[new-subclass]">
        <h1>Not Featured Item</h1>
        <p>Lorem ipsum...</p>
    </div>
</div>
```

Similarly, if the featured item were the last one, it might be something like:

``` html
<div class="[new-class]">
    <div class="[new-subclass]">
        <h1>Not Featured Item</text-small>
        <p>Lorem ipsum...</p>
    </div>
    <div class="[new-subclass]">
        <h1>Not Featured Item</h1>
        <p>Lorem ipsum...</p>
    </div>
    <div class="[new-subclass] featured">
        <h1>Featured Item</h1>
        <p>Lorem ipsum...</p>
    </div>
</div>
```

We might actually be able to reuse the `panel` concept for these subclasses (the one listed as `[new-subclass]`). This would keep terminology familiar. The question then becomes what the `[new-class]` becomes. It would need to be a flexible name to support multiple different sorts of arrangements, since we might have 1-3, 1-4, 2-4, etc. arrangements. One thought so far is possibly using `region-SOMETHING` so like you might have `region-1-2` or `region-2-2` (in which case, the `featured` class or something of that style isn't even necessary since the classes become context-specific) but that just seems inelegant. We could use some thoughts about better semantics for these sorts of things - I mean a list might even make more sense than divs (enforces that there are only elements that are of the `[new-subclass]` without even having to state this subclass explicitly. The negative to a list would be that it makes the style very different than panels (although you can actually use a ul > li pattern for .row > .panel).

We also might be interested in arrangements where there are four panels like this:

```
[-][-][-][-]
```

And then they cascade like this:

```
[----][----]
[----][----]
```

And finally they cascade into the regular rows like this:

```
[----------]
[----------]
[----------]
[----------]
```

If we go with the multiple breakpoints for panelling like in #174, this behavior is supported:

``` html
<div class="row medium-collapse">
    <div class="panel-6">
        <div class="row small-collapse">
            <div class="panel-6">
            </div>
            <div class="panel-6">
            </div>
        </div>
    </div>
    <div class="panel-6">
        <div class="row small-collapse">
            <div class="panel-6">
            </div>
            <div class="panel-6">
            </div>
        </div>
    </div>
</div>
```

However, in some of the arrangements we consider in this ticket, we might find ourselves providing a cleaner set of semantics (rather than a grid within a grid) to establish this sort of behavior.

Thoughts?

/CC @loganfranken @lnicks @chris4ucla @jeff1evesque @edsakabu @ccheung @atsengucla

**Comment by ebollens** [comment]
@loganfranken @lnicks @chris4ucla @jeff1evesque @edsakabu @ccheung @atsengucla any opinions here?

**Comment by loganfranken** [comment]
Hey @ebollens: sorry for the wait on a response!

I'm a little confused by the first example. If I'm understanding this correctly, we would have the following:

```
[--Featured Item---]
[--Item--][--Item--]
```

And then, on a smaller viewport, we have:

```
[--Featured Item--]
[------Item-------]
[------Item-------]
```

Right?

I actually don't see a problem here: it would make sense for the top item to still have a larger font size since it is still a featured item at the top of the list.

However, I do think it's important to address the use case you describe with the diagram. I'm not coming up with anything inspiring at the moment: maybe we can further discuss possible semantics in today's meeting?

**Comment by ebollens** [comment]
Yeah, let's discuss more at today's meeting. Moving this back to next milestone for completion.

**Comment by ebollens** [comment]
Any more feedback on this?

**Comment by lnicks** [comment]
Apologies if I'm a bit fuzzy here, first day back...but here are my thoughts from a CMS point of view:

It's difficult (not impossible, but not fun) to modify semantics on an individual record within a set of content.  First-child and other pseudo selectors are our options, anything else would require us to program for individual cases.  We have a lot of control over the container itself, and we can provide a template for each record, but to add potentially varying classes, we'd have to go through some serious trouble.

My understanding of webblocks is limited, but some kind of parallel to the first child concept, which changes behavior based on breakpoints, like the first solution, would be more useful to us (region-1-2 etc).   I would think in this case, the only thing that matters is the container / first record (unless the goal is to take this further, and I'm not sure I'd ever do that).

**Comment by ebollens** [comment]
@lnicks the goal of this goes beyond the CMS case, although if you're writing HTML markup into something in the CMS, this could be useful. However, as this is talk about introducing a whole new slew of semantics, I am going to remove it from milestone 0.1.06 - slated instead for more long-term discussion.

**Comment by ebollens** [comment]
The cluster (#492) element was one of the ones we added here. If someone has other proposals, please open issues from them.
