### ISSUE TITLE
img[srcset] Polyfill

### ISSUE THREAD

**Issue by ebollens** [ucla-oarc-web/WebBlocks#186]
In some cases, a user simply wants to size up image themselves into several common sizes and then define these paths and let the browser pick the best one based on device dimensions. To this end, there are two standards bouncing around the image community: `img[set]` (just entered into the HTML 5 ED) and `picture` (proposed by RICG). A good article can be found on A List Apart: [Responsive Images and Web Standards at the Turning Point](http://www.alistapart.com/articles/responsive-images-and-web-standards-at-the-turning-point/). Regardless of which one is eventually picked in the debate, this sort of thing is needed now, and several polyfills exist for `picture`:
- jQuery Picture http://jquerypicture.com
- Picturefill https://github.com/scottjehl/picturefill

Another example exists that uses `data-src-` prefix:
- http://nicolasgallagher.com/responsive-images-using-css3/

I lean away from this one though because it requires explicit CSS definitions as well.

~

NOTE: https://github.com/ucla/WebBlocks/issues/186#issuecomment-24555182 updates this.

Goal is to polyfill `img[srcset]`.

**Comment by loganfranken** [comment]
I just wanted to leave links to the Responsive Images Community Group, a group that's been doing some wonderful work in developing and tracking the progress of this issue:

http://www.w3.org/community/respimg/
http://responsiveimages.org/

**Comment by ebollens** [comment]
This has been moved back to milestone 0.1.07.

**Comment by ebollens** [comment]
The `img[srcset]` attribute is ED status with the W3C:

> http://www.w3.org/html/wg/drafts/srcset/w3c-srcset/

Therefore, we should prefer this approach.

There's already a polyfill with unit tests to conform with the ED:

> https://github.com/borismus/srcset-polyfill

We may still want to offer jQuery Picture as an alternate, as it is a syntax already familiar to developers from `video` and `audio` tags, and it isn't in violation of anything technically - albeit that it won't be implemented.

**Comment by spiritcapsule** [comment]
link above to w3c is broken due to a missing trailing slash. here's a working link:
http://www.w3.org/html/wg/drafts/srcset/w3c-srcset/

i'm a bit surprised that a missing trailing slash would result in a 404 on w3.org!

**Comment by ebollens** [comment]
Fixed in my comment. It's probably a routing error.
