### ISSUE TITLE
Polyfills for Missing Image Support

### ISSUE THREAD

**Issue by ebollens** [ucla-oarc-web/WebBlocks#187]
Older versions of Internet Explorer do not support max-width. While we've said we're not explicitly going to support old versions of IE, there are two fixes to this that are trivial:
- Use AlphaImageLoader directly in sheets (only works for framework files or when users actually define it)
- Method using Javascript to do it dynamically: http://unstoppablerobotninja.com/entry/fluid-images/ (remake of imgSizer.js)
- Use this method: http://css-tricks.com/ie-fix-bicubic-scaling-for-images/

A similar issue comes from transparent PNGs, and the fix is again trivial:
- dd_belatedPNG http://www.dillerdesign.com/experiment/DD_belatedPNG

However, the question with all of these support polyfills is whether they make sense to provide or we just say "eff it" to old, unsupporting browsers.

**Comment by loganfranken** [comment]
Are we planning on establishing a baseline of browser support across the board or on a feature-by-feature basis? In other words, "Everything works in IE8 and above" vs. "Responsive images do not work in IE8, but everything else does." I'm leaning towards the former for simplicity, although I could see the value in the latter given the wide featureset of Web Blocks.

**Comment by ebollens** [comment]
I'd like to shoot for as much of "Everything works in IE8 and above" as possible, but I will reneg in some cases if implementation isn't friendly. So far, we haven't done much on the lines of IE testing. I'm happy to say IE 8 and above. The blocks-ie.css file is to be loaded for IE < 9.

**Comment by ebollens** [comment]
This has been moved back to milestone 0.1.07.

**Comment by ebollens** [comment]
Decided no reason to include dd_belatedPNG - who the hell uses IE6 and expects anything to look good anymore? However, I do see some validity in packing a scaling technique for IE7 and old FF. The `-ms-interpolation-mode: bicubic` technique only works for JPEG, so I'd like to use Ethan Marcotte's solution; however, there's no license on it, so I've pinged Ethan to see if he can provide some clarity.

In the meantime, I'm going to throw this in a package and leave it in a branch with an open pull request.
