### ISSUE TITLE
Core Adapter Nav/List & Nav/Breadcrumb Styling

### ISSUE THREAD

**Issue by ebollens** [ucla-oarc-web/WebBlocks#198]
@loganfranken I have implemented a complete core adapter in #137 with the exception of the `Entity/Nav/List` and `Entity/Nav/Breadcrumb` styles. The purpose of having a core adapter that is fully styled is to make it possible, if you're not using Bootstrap, to just leverage WebBlocks semantics without having to compile all of that extra CSS.

You can either (a) mooch straight from Bootstrap like I did for some aspects like buttons or (b) implement a variant that looks smooth using your own take on what these elements should look like.

**Comment by loganfranken** [comment]
Moving to next milestone

**Comment by ebollens** [comment]
Any update on this?

**Comment by loganfranken** [comment]
No update on this; I'll do my best to try and get to it but I can't guarantee it, unfortunately.

**Comment by ebollens** [comment]
This has moved to 0.1.07 and we'll just compile with Bootstrap adapter for the moment.

**Comment by ebollens** [comment]
Reassigning this to myself to complete.
