### ISSUE TITLE
Entity/Nav/List Prototype

### ISSUE THREAD

**Issue by alicetseng** [ucla-oarc-web/WebBlocks#20]
@loganfranken do you want to take a crack at the nav list prototype? I'm collecting research on best practice on the wiki page and examples.

**Comment by loganfranken** [comment]
Thanks for the research @atsengucla; I put up a draft of the prototype and added some discussion in the wiki: https://github.com/ucla/WebBlocks/wiki/Entity-nav-list When you get a chance, would you mind giving me some feedback?

Also, a reminder to myself (or anyone else who wants to give it a shot): we need to tackle adding "dividers" to the menu. I'm really not a fan of Twitter Bootstrap's empty `li` with a `divider` class approach. Maybe if a `nav` contains multiple `ul`s this could automatically create a divider between them?

**Comment by alicetseng** [comment]
Hi Logan,
Apologies for the lag in response-- I've updated the wiki page.
Cheers,
Alice

On 7/26/12 11:53 PM, "Logan Franken"
<reply+i-5858521-9c69a3f5d4b9794b1100f7611f8a90aab12da727-1393130@reply.git
hub.com> wrote:

**Comment by loganfranken** [comment]
Thanks for the feedback @atsengucla!

I removed the "toggle" option for simplicity and incorporated your suggestions (adding support for headers and accordion/flyout menus). I also updated the README with an explanation of all the changes.

A couple things that may need to spawn separate issues:
- I added a "Features" section to the README to include explanations of the various components of the entity template. What does everyone think of this? Should we add this to the main README template?
- You also mentioned ARIA integration. That brings up a good point: I was actually thinking we should make ARIA a separate task where we run through all of our entity templates and decide if they need to be enhanced with ARIA suggestions. Thoughts?

**Comment by ebollens** [comment]
We should incorporate the features section into the readme, yes.

**Comment by ebollens** [comment]
@loganfranken, based on the toggle portion here, should we carry this over into `Entity/Nav/Main` as well? It defines an explicit button right now.

**Comment by loganfranken** [comment]
The "Features" section was added to the README template:
https://github.com/ucla/WebBlocks/wiki/Creating-an-Entity-Prototype

@ebollens Yes, I think so, unless @atsengucla disagrees.

Also, @atsengucla, I updated the wiki with a more in-depth discussion of the semantics of the two types of list markup (with a final note about how it likely doesn't matter for plain lists):
https://github.com/ucla/WebBlocks/wiki/Entity-nav-list

Barring any other concerns/updates (please let me know if there are!), I'll mark this entity as ready for the next stage.

**Comment by ebollens** [comment]
@loganfranken when you guys have pinned down the toggle on this one, want to carry it into the other prototype then as well? I'm currently working on trying to clean up modularity in the architecture.

**Comment by loganfranken** [comment]
@ebollens Will do!

**Comment by loganfranken** [comment]
Migrated to development stage: #64
