### ISSUE TITLE
Incorrect Page Titles in .md doc Files

### ISSUE THREAD

**Issue by jwatkin** [ucla-oarc-web/WebBlocks#220]
Several .md doc files have incorrect page titles.

Module.md - the interior title is pluralized which is inconsistent with the file name.

It looks like these files have copy-and-paste typos for titles:
base/Type.md
base/Visibility.md
entity/Message.md

In the entity page titles, a slash is used where a hyphen is used in the file name. Should the interior title match the file name?

The base page titles contain "Base/" prefixes. The entity page titles don't contain an "Entity/" prefix. Shouldn't they use a consistent prefix scheme?

**Comment by ebollens** [comment]
@jwatkin thanks for the continuity catches. Assigning to myself to fix for 0.1.06 milestone.

**Comment by ebollens** [comment]
The reason for the filenames having hyphens in them even though the titles have slashes is that I'm trying to just do a two-tier file structure, not bury everything layers deep - but by module name (if you're building WebBlocks with configuration options) there's slashes.

Besides that, the other fixes are now in.
