### ISSUE TITLE
submodule modernizr failed on build

### ISSUE THREAD

**Issue by jrosczyk** [ucla-oarc-web/WebBlocks#224]
Got this error on build:
[Submodule: modernizr] Initialization failed for submodule modernizr rake aborted!

**Comment by ebollens** [comment]
@jrosczyk any further indication of what is happening? This is the first package that the compiler tries to pull down (default behavior at least). If there aren't any further errors being output, could you provide information on your environment (OS, Ruby version, etc.)? Also, did it used to work, and if so, which commit broke it?

**Comment by jrosczyk** [comment]
I'm starting a new project, so I grabbed a fresh build. My environment uses OSX 10.8.2 and Ruby 1.9.3.

```
[Rake] Attach packages
  [Package] Attached package handler jquery
  [Package] Attached package handler modernizr
  [Package] Attached package handler respond
  [Package] Attached package handler selectivizr
  [Package] Attached package handler efx
[Rake] Attach adapters
  [Core] Attached Core handler Adapter
  [Adapter] Attached Adapter handler Bootstrap
  [Core] Attached Core handler Extensions
  [Core] Attached Core handler Definitions
[Rake] Attach WebBlocks composer
  [WebBlocks] Attached blocks handler
[Rake] Load task definitions
** Invoke default (first_time)
** Invoke build (first_time)
** Invoke init (first_time)
** Execute init
[Dispatcher] Executing task: before_init
[Dispatcher] Executing task: init
  [WebBlocks] Initializing WebBlocks metadata
[Dispatcher] Executing task: after_init
** Execute build
[Dispatcher] Executing task: before_preprocess
[Dispatcher] Executing task: preprocess
  [Submodule] Initializing submodule modernizr
    [Submodule: modernizr] Initialization failed for submodule modernizr
rake aborted!
```

**Comment by ebollens** [comment]
What happens if you just type `git submodule init` and then `git submodule update` from within the WebBlocks repository root?

**Comment by jrosczyk** [comment]
That works. Using it as a submodule is probably better anyways. Thanks.

**Comment by ebollens** [comment]
I think I'm going to add some instructions to the documentation that ask you to call `git submodule init` and `git submodule update` before running WebBlocks. It's not as elegant as just having the user run `rake` and have it do all the checkouts itself, but better than nothing.
