### ISSUE TITLE
Container not adhering to max width

### ISSUE THREAD

**Issue by lnicks** [ucla-oarc-web/WebBlocks#225]
```
$structure-container-gutter:    3%;
$structure-container-width-max: 960px; 
```

Here's what I have in the _variables.scss file.

Unsure if my syntax is wrong or not.

Branch `[app/dentistry]` updated for example.

/cc @ebollens @chris4ucla

**Comment by ebollens** [comment]
Please provide some sample markup to replicate.

**Comment by lnicks** [comment]
This was posted before we realized the compiler is broken.  I'm not sure the initial problem is related to the container, if our settings weren't being added.

**Comment by ebollens** [comment]
I am closing this as I cannot replicate the issue you're reporting regarding `.container`.
