### ISSUE TITLE
Support List Element Within Entity/Form

### ISSUE THREAD

**Issue by loganfranken** [ucla-oarc-web/WebBlocks#230]
In my experience, structuring forms with `form>ul>li` is a common, semantic practice:

```
<form>
    <ul>
        <li>
            <label for="signin-username">UCSB Net ID</label>
            <input type="text" id="signin-username" name="username" />
        </li>
        <li>
            <label for="signin-password">Password</label>
            <input type="password" id="signin-password" name="password" />
        </li>
        <li>
            <input type="submit" value="Sign In" class="button" />
        </li>
    </ul>
</form>
```

I was hoping we could extend the Entity/Form element to allow `.control` to be applied to inner `li` elements as well?

**Comment by ebollens** [comment]
Sounds like a completely reasonable idea. I like the idea of making a form a list (except for the whole multiple fieldsets bump, in which case each fieldset becomes its own list).

**Comment by ebollens** [comment]
This has been moved back to milestone 0.1.07 as it is a non-critical feature add-on.

**Comment by loganfranken** [comment]
Went ahead and fixed this as I need it for a project.

Hrm, sorry about the large diffs: I'm not exactly sure why my editor keeps arguing with GitHub diff over the line-endings. I'm using Visual Studio with the encoding set to UTF-8 w/o signature because I thought that would be as plain Jane as I could get encoding-wise.

**Comment by loganfranken** [comment]
The list implementation has different padding than the regular implementation.
