### ISSUE TITLE
Add Support for Rugby Stripe type themes

### ISSUE THREAD

**Issue by spiritcapsule** [ucla-oarc-web/WebBlocks#243]
in a rugby stripe theme, there is usually a max-width on the page container (960px for example) and the background colors of the page sections (banner/masthead, nav, content, footer) extend to the left and right beyond the boundaries of the sections and containers, usually to the window's edge

right now, this requires a hack with webblocks

**Comment by loganfranken** [comment]
Hey @chris4ucla, would you happen to have an example of this?

I'm working on a project right now with Web Blocks, and I just use an element to contain a `.container` element when I want background colors to extend beyond the reach of the responsive container:

``` html
<div class="ucsb-banner">
    <a href="http://www.ucsb.edu/" target="_blank" class="container">University of California, Santa Barbara</a>
</div>
```

Not sure if you're referring to something else, though?

**Comment by spiritcapsule** [comment]
On another project @ebollens and I were working on, we were trying to center a horizontal nav menu. Eric had to modify a little more than he seemed to want to. He called his solution hacky... So we're just talking about making this a little cleaner to implement.

```
  <div class="primary gradient" style="margin-bottom:1em; overflow:hidden;">
      <nav id="navigation" class="primary bar container">
          <!-- .. -->
      </nav>
  </div>

  <style>
      nav.bar.overflow > .toggle.auto {
          margin-right: 40px;
      }
  </style>

```

**Comment by ebollens** [comment]
@loganfranken the problem specifically relates to the navbar.

**Comment by ebollens** [comment]
I'm unconvinced why we need this instead of the form:

``` html
<header class="container">
    <!-- header in container -->
</header>
<nav class="bar">
    <!-- full-width nav bar -->
</nav>
<main class="container">
    <!-- main content in container -->
</main>
<footer class="container">
    <!-- footer in container -->
</footer>
```

I think the issue arrises when one wants to put a full-width nav inside of an element that has `.container` applied to it. @chris4ucla or anyone else, any reason why the above prototype doesn't work? Closing until such time as shown otherwise.
