### ISSUE TITLE
Need a "Hide Above"

### ISSUE THREAD

**Issue by StillSlippery** [ucla-oarc-web/WebBlocks#248]

**Comment by ebollens** [comment]
I have now added a set of classes `hide-above-X` that allow you to hide content above a certain breakpoint. Basically, if you use `.hide-small`, content will only be visible above `$breakpoint-small`, whereas if you use `.hide-above-small`, then content will only be visible at and below `$breakpoint-small`.

/CC @lnicks @chris4ucla @jeff1evesque @loganfranken

**Comment by lnicks** [comment]
Using `.hide-above-small` is not working for me on http://dentistrydev.oit.ucla.edu.  Unsure if I have had a problem updating with git or if it's not working.  Not sure how to check.

**Comment by lnicks** [comment]
Also, can this functionality be used as such:

`[panel-8][panel-4 hide-above-small][panel-4 hide-small]`

Edit: hide-small

**Comment by ebollens** [comment]
See my email. It failed to push the update until now.

On Feb 5, 2013, at 11:44 AM, "lnicks" <notifications@github.com<mailto:notifications@github.com>> wrote:

Using .hide-above-small is not working for me on http://dentistrydev.oit.ucla.edu. Unsure if I have had a problem updating with git or if it's not working. Not sure how to check.

**Comment by ebollens** [comment]
Not with guarantees effect. But how is it diff from putting two divs inside the panel-4?

On Feb 5, 2013, at 12:00 PM, "lnicks" <notifications@github.com<mailto:notifications@github.com>> wrote:

Also, can this functionality be used as such:

[panel-8][panel-4 hide-above-small][panel-4 hide-below-small]

**Comment by lnicks** [comment]
I may have butchered that.

I mean using it like a conditional, and there are two panel-4s and only one is active at a time, even though the amount in the DOM adds up above 12 (in this case, 12 are active, 16 total).

Essentially conditional content based on screen size.

**Comment by ebollens** [comment]
No, I understood what you meant. Use a single panel with two divs inside with the visibility controls on those. This is because panels themselves use nth child selectors, so their existence in the DOM will lead them to be styled potentially differently, even if only one shows at a time.

**Comment by lnicks** [comment]
So if I'm understanding this correctly, this is extremely useful.

/CC @chris4ucla @ssantaana @jeff1evesque

**Comment by lnicks** [comment]
Still not having any luck with `.hide-above-small`.

**Comment by lnicks** [comment]
Nevermind!
