### ISSUE TITLE
Compiling CSS only

### ISSUE THREAD

**Issue by lnicks** [ucla-oarc-web/WebBlocks#251]
I know there's a way to compile only the css, but after looking through the documentation and I couldn't find it.  

/CC @chris4ucla @ssantaana @jeff1evesque @ebollens

**Comment by ebollens** [comment]
To quote directly from `README.md`:

> `rake build_css` compiles CSS only (!)

**Comment by lnicks** [comment]
Yeah so I only looked through the doc folder.  Thanks!
