### ISSUE TITLE
.panel-X only as direct child of .row

### ISSUE THREAD

**Issue by ebollens** [ucla-oarc-web/WebBlocks#263]
I've discovered a bug in implementation of `Y-collapse`: if nesting rows three layers deep, then gutter bugs may manifest. To generate this, try:

``` html
<div class="row small-collapse">
  <div class="panel-12">
    <div class="row medium-small-collapse">
      <div class="panel-12">
        <div class="row medium-small-collapse">
          <div class="panel-6">A</div>
          <div class="panel-6">B</div>
      </div>
    </div>
  </div>
</div>
```

This will pad incorrectly.

As such, I propose a modification to the semantics: `.panel-X` definitions use direct child selector.

This would prevent you from doing the following:

``` html
<div class="row">
  <div>
    <div class="panel-6">A</div>
    <div class="panel-6">B</div>
  </div>
</div>
```

I don't see a reason why this would be useful anyways.

Meanwhile, we gain two big wins:
1. Supported more than two layers of nesting of explicit collapse control rows.
2. Reduction of CSS definition size and complexity.

Anyone see problems with this?

/CC @loganfranken @lnicks @edsakabu

**Comment by lnicks** [comment]
I have not had a need to nest that deep yet, don't think I will either.

I don't see what the problem is with requiring the relationship, I haven't run into any situations where that would be advantageous.
