### ISSUE TITLE
Request: Offline-only directive for Webblocks Compiler

### ISSUE THREAD

**Issue by lnicks** [ucla-oarc-web/WebBlocks#273]
An option that would only compile the CSS would be helpful in our cases where we use a development server.  I don't expect people to stop using that method with webblocks, and the current implementation takes a while to wait for a compile, for even the smallest changes.

Would be a super time saver.

/cc @ebollens @chris4ucla @rrocchio

**Comment by loganfranken** [comment]
Just in case I'm missing something: would this be different than the `build_css` option that only compiles the CSS?

**Comment by ebollens** [comment]
Yes, the `build_css` task still does the `git submodule` stuff. What @lnicks is asking for is basically something that bypasses this step altogether. To make it generic across `build` and all the `build_` tasks, this would be an option in the invocation of rake kind of like `--config`.

**Comment by ebollens** [comment]
Sorry, this comes from a discussion in another location, which is why I know he's shooting for this in particular.

**Comment by lnicks** [comment]
Yeah, apologies for not being clearer.  It's just for rapid prototyping where only a line or two of css gets changed and that's it.
