### ISSUE TITLE
Custom CSS Build Directories Not Working

### ISSUE THREAD

**Issue by loganfranken** [ucla-oarc-web/WebBlocks#274]
I could be setting this up wrong, but I wanted Web Blocks to drop the CSS and JS files directly into the file structure of my existing project, so I added the following setting to the configuration file:

`WebBlocks.config[:build][:dir] = "D:/Projects/WebsiteUsingWeblocks"`
`WebBlocks.config[:build][:css][:dir] = "style"`

Actually, just to make sure it's clear what's happening, let's set it to this:

`WebBlocks.config[:build][:dir] = "D:/Projects/WebsiteUsingWeblocks"`
`WebBlocks.config[:build][:css][:dir] = "custom-weblocks-css"`

This ends up causing the Web Blocks Builder to do the following:

`Copying C:/WebBlocks/.build-tmp/custom-weblocks-css/blocks.css to D:/Projects/WebsiteUsingWeblocks/custom-weblocks-css/blocks.css`

The problem here is that we actually want the file from `C:/WebBlocks/.build-tmp/css` copied over. The version sitting in `C:/WebBlocks/.build-tmp/custom-weblocks-css` is some bizarre truncated version of the file.

**Comment by ebollens** [comment]
@loganfranken what happens if you set it this way:

``` rb
WebBlocks.config[:build][:dir] = "D:/Projects/WebsiteUsingWeblocks"
WebBlocks.config[:build][:css][:dir] = "#{WebBlocks.config[:build][:dir]}/style"
```

I know this is not ideal, but is it a viable workaround?

**Comment by ebollens** [comment]
It also dawned on me that Ruby might not be treating these as absolute paths, although I have no idea.

**Comment by ebollens** [comment]
It appears that part of the problem here is that WebBlocks attempts to use the directory name from the configuration setting as what it generates in `.build-tmp`. The top of a log from @uncleerniebs where he specified a path for the CSS directory and it's trying to create that as the temporary directory:

```
undefined method `to_str' for false:FalseClass
/usr/lib/ruby/1.8/fileutils.rb:1395:in `fu_list'
/usr/lib/ruby/1.8/fileutils.rb:1395:in `map'
/usr/lib/ruby/1.8/fileutils.rb:1395:in `fu_list'
/usr/lib/ruby/1.8/fileutils.rb:606:in `rm_r'
/usr/lib/ruby/1.8/fileutils.rb:635:in `rm_rf'
/home/user/plone-Weblocks/lib/Build/WebBlocks.rb:46:in `preprocess_css'
/home/user/plone-Weblocks/lib/Build/Adapter/../../Logger.rb:40:in `task'
/home/user/plone-Weblocks/lib/Build/Adapter/../../Logger.rb:87:in `scope'
/home/user/plone-Weblocks/lib/Build/Adapter/../../Logger.rb:39:in `task'
/home/user/plone-Weblocks/lib/Build/WebBlocks.rb:43:in `preprocess_css'
/home/user/plone-Weblocks/lib/Build/WebBlocks.rb:33:in `preprocess'
```

**Comment by loganfranken** [comment]
Hey @ebollens, thanks for the suggestion, but strangely enough, that actually causes the Builder to copy the file over onto itself:

`Copying D:/Projects/WebsiteUsingWebBlocks/style/blocks.css to D:/Projects/WebsiteUsingWebBlocks/style/blocks.css`

This isn't holding me up at all: I just directed the output to a different directory for right now.

**Comment by ebollens** [comment]
Okay, well it's an issue that conflicts with the documentation, so we'll need to resolve it.
