### ISSUE TITLE
Entity/Nav/Tabs

### ISSUE THREAD

**Issue by loganfranken** [ucla-oarc-web/WebBlocks#298]
Ran into a project today where I needed in-page, tabbed subnavigation:
http://twitter.github.com/bootstrap/components.html#navs

Not sure if we had plans to fold this into another navigation entity, but thought I would plop it down here.

**Comment by ebollens** [comment]
As part of this, I'd like to include a tab system. Efx can likely be leveraged to help.

**Comment by ebollens** [comment]
From https://github.com/ucla/WebBlocks/wiki/Meeting-2013-11-18...

Basic prototype identical to other nav patterns:

``` html
<nav class="tabs">
    <h1>Optional Title</h1>
    <ul>
        <li><a data-target="#tab-1">Tab 1</a></li>
        <li><a data-target="#tab-2">Tab 2</a></li>
    </ul>
</nav>
```

An example using EFX:

``` html
<div data-effect="tabs">

    <nav class="tabs">
        <h1>Optional Title</h1>
        <ul>
            <li><a data-target="#tab-1">Tab 1</a></li>
            <li><a data-target="#tab-2">Tab 2</a></li>
        </ul>
    </nav>

    <section id="tab-1" data-tabs="show">
        <h2>First Tab</h2>
        <p>This is content for the first tab</p>
    </section>

    <section id="tab-2">
        <h2>Second Tab</h2>
        <p>This is content for the second tab</p>
    </section>

</div>
```

**Comment by spiritcapsule** [comment]
Does an anchor with data-target but no href receive focus?
`<a data-target="#tab-1">Tab 1</a>`
cc// @lnicks

**Comment by ebollens** [comment]
@chris4ucla I've created a separate issue for your question in the ebollens/efx repository where it belongs. This issue is related to the presentation of `nav.tabs`.
