### ISSUE TITLE
Error with 'rake build' -- undefined local variable 'rootdir'

### ISSUE THREAD

**Issue by alroman** [ucla-oarc-web/WebBlocks#300]
Using WebBlocks as submodule as directed in the docs (http://ucla.github.com/WebBlocks/doc/#Recipe/Integration/Submodule) with example Rakefile.  With ruby version: ruby 1.9.3p362 (2012-12-25 revision 38607) [x86_64-linux]

When running `rake build` I see the following error after the `_init` task:

``` sh
...
npm install
** Execute build
rake aborted!
undefined local variable or method `rootdir' for #<WebBlocks:0x000000016148a0 @path="blocks">
/var/www/moodle-blocks/moodle/theme/uclashared/Rakefile:13:in `block in rake'
/var/www/moodle-blocks/moodle/theme/uclashared/Rakefile:10:in `chdir'
/var/www/moodle-blocks/moodle/theme/uclashared/Rakefile:10:in `rake'
/var/www/moodle-blocks/moodle/theme/uclashared/Rakefile:28:in `block in <top (required)>'
...
```

I am able to resolve this issue by redeclaring `rootdir` in WebBlocks' rake method:

``` ruby
  def rake(command = '')
    Dir.chdir @path do
        rootdir = "/path/to/moodle/theme/uclashared"
        sh "rake #{command} -- --config=#{rootdir}/Rakefile-config.rb"
    end
  end

```

**Comment by ebollens** [comment]
Does this work if you set the following:

``` rb
  def rake(command = '')
    Dir.chdir @path do
        rootdir = File.dirname(Pathname.new(__FILE__).realpath)
        sh "rake #{command} -- --config=#{rootdir}/Rakefile-config.rb"
    end
  end
```

The reason I ask is that I'd like to make it more generic than absolute path.

**Comment by alroman** [comment]
Yes that works for me.

**Comment by ebollens** [comment]
Easy fix in docs then :-)

On Feb 22, 2013, at 8:23 AM, "Alfonso Roman" <notifications@github.com<mailto:notifications@github.com>> wrote:

Yes that works for me.
