### ISSUE TITLE
Modify Instructions for Creating Entity Prototypes

### ISSUE THREAD

**Issue by loganfranken** [ucla-oarc-web/WebBlocks#304]
To avoid bloating the size of the repo again, should we modify our approach (and the corresponding instructions) for creating new entity prototypes?

https://github.com/ucla/WebBlocks/wiki/Creating-an-Entity-Prototype

**Comment by ebollens** [comment]
Yes, we should.

I'm inclined to support the following:
- Create an issue
- Describe a prototype
- Upload images (GitHub just added support for attaching images to comments)
- When all is finalized, the final comment that closes it should sum up everything decided
- Documentation kind of replaces what we were doing in `/templates` earlier

**Comment by loganfranken** [comment]
Sounds good @ebollens

I updated the wiki article with that information:
https://github.com/ucla/WebBlocks/wiki/Creating-an-Entity

I also modified the wiki article to cover all stages of creating an entity (from prototyping to implementation). Related to that, the article now instructs developers to only create one GitHub issue to cover all stages, rather than one for prototyping and another for implementation. That seemed to fit better with the current development practices, but please feel free to change it if you disagree.
