### ISSUE TITLE
Variables in 'src/sass' dir do not override 'type-*' default variables

### ISSUE THREAD

**Issue by alroman** [ucla-oarc-web/WebBlocks#318]
I am able to override `$color-branding-default`, but not `$type-font-size` in my _variables.scss file.  

I would also suggest having scaled values for h# elements instead of hard-coded values.  This is similar to what sass-twitter-bootstrap does:

``` scss
$type-font-size:                 1em;
$type-font-size-h1:              $type-font-size * 1.385;
$type-font-size-h2:              $type-font-size * 1.231;
$type-font-size-h3:              $type-font-size * 1.08;
...
```

**Comment by ebollens** [comment]
Good catch. These are missing the `!default` qualifier.

**Comment by ebollens** [comment]
The values are not hardcoded. Their `em`-based. However, Bootstrap does override them currently, which is a separate issue that's covered in #266.

**Comment by ebollens** [comment]
Note that this issue is marked as fix because I've added the `!default` qualifiers that were missing. It is _not_ fixed where compiled with the Bootstrap adapter, as right now the adapter still hardcodes its own styles. That's a separate issue in #266.
