### ISSUE TITLE
Breadcrumbs

### ISSUE THREAD

**Issue by ebollens** [ucla-oarc-web/WebBlocks#338]
Missing doc and core adapter here.

**Comment by ebollens** [comment]
Thanks for all the pull requests on this one! Anything remaining on it?

**Comment by loganfranken** [comment]
Thank _you_! Happy to be getting back to some work on WebBlocks.

And: nope, this is all finished, unless I need to do a special Pull Request for `gh-pages`? Let me know, but I'll close the issue for now.
