### ISSUE TITLE
.button.small is not available without including bootstrap adapter

### ISSUE THREAD

**Issue by alroman** [ucla-oarc-web/WebBlocks#349]
The `button.small` rule is not created when setting the following config:

``` ruby
WebBlocks.config[:src][:adapter] = false
```

The rule is created when I include the default adapter as so:

``` ruby
WebBlocks.config[:src][:adapter] = 'bootstrap'
```

In my case, I find it necessary to prevent boostrap from loading since it overrides Moodle's default styles due to class names collisions.

**Comment by ebollens** [comment]
This was resolved in some previous commit.
