### ISSUE TITLE
Mega Menu for Gateway Template

### ISSUE THREAD

**Issue by chentarry** [ucla-oarc-web/WebBlocks#351]
Here is the mega menu I brought up during the discussion earlier - it's actually the menu on the current www.ucla.edu page (it's the menu beneath the Google search bar on the top right). 

http://www.ucla.edu/

It should be the white menus with the header text reading: "About", "Academics", "Admissions"...

Hope this helps your development of making MegaMenu entities. We look forward to seeing your work and please let me know if you have any questions!

**Comment by ebollens** [comment]
An example of the UCLA-specific implementation is available here:
https://github.com/ucla/WebBlocks-kit-core (used in https://github.com/ucla/WebBlocks-kit)

Discussion on the mega-menu, which is based off this, is available under #449 - although development on this entity as WebBlocks core is stalled on the grounds of needing someone to provide a design that is not campus specific (semantics are established, and implementation is working, but we need something that feels generic). Consequently, closing this issue as superseded by the other one.
