### ISSUE TITLE
External Adapter Support

### ISSUE THREAD

**Issue by alroman** [ucla-oarc-web/WebBlocks#355]
I've been writing a custom adapter I've had have to add my own file to `lib/Build/Adapter' in order to achieve this.  It would nice to have a way to specify an adapter outside WebBlocks since I use it as a submodule.

Better yet, if it were possible to define an object in my `Rakefile-config.rb` that would specify what I need to build.

**Comment by ebollens** [comment]
In talking with @alroman about this on Monday, the goal will be that, when you specify an adapter, you can do so either with a string (using the default load methodology) or an object that lets you set the path to your adapter handler and your adapter sources. This will go into milestone 0.2.00 once we get past the beta.

**Comment by ebollens** [comment]
The file that will need to be modified to support this:
https://github.com/ucla/WebBlocks/blob/master/lib/Build/Manager.rb

**Comment by ebollens** [comment]
The addition to support this follows the vein of:

``` ruby
WebBlocks.config[:src][:search][:adapter]['example'] = {
  :class => 'ExampleAdapter::Handler',
  :path => '/absolute/path/to/example_adapter/handler.rb'
}

WebBlocks.config[:src][:adapter] = 'example'
```

Once inside your own adapter handler, you're free to implement whatever logic you'd like. The documentation in [Core/Architecture/Adapter](http://ucla.github.io/WebBlocks/doc/#Core/Architecture/Adapter) may be of help - however, keep in mind that some of the methods used in the example code assume `include` statements for WebBlocks helpers, but they are not necessary and one can code an adapter to do anything they want.

The rule of thumb around adapters is that you should define methods by the names of the tasks that you see in the compiler when you do a run. Consider a run like `build_css`. You see the following output when calling `rake build_css`:

```
[Dispatcher] Executing task: before_init
[Dispatcher] Executing task: init
[Dispatcher] Executing task: after_init
[Dispatcher] Executing task: before_preprocess_css
[Dispatcher] Executing task: preprocess_css
[Dispatcher] Executing task: after_preprocess_css
[Dispatcher] Executing task: before_link_css
[Dispatcher] Executing task: link_css
[Dispatcher] Executing task: after_link_css
[Dispatcher] Executing task: before_compile_css
[Dispatcher] Executing task: compile_css
[Dispatcher] Executing task: after_compile_css
[Dispatcher] Executing task: before_assemble_css
[Dispatcher] Executing task: assemble_css
[Dispatcher] Executing task: after_assemble_css
[Dispatcher] Executing task: before_package_css
[Dispatcher] Executing task: package_css
[Dispatcher] Executing task: after_package_css
[Dispatcher] Executing task: before_postprocess_css
[Dispatcher] Executing task: postprocess_css
[Dispatcher] Executing task: after_postprocess_css
```

You can define a method within your adapter handler by any of these names, such as:

``` ruby
def link_css
  # whatever steps you do during compile, such as appending to the linker files
end

def assemble_css
  # whatever steps you do during assembly, such as appending source files
end
```

Of course, to make sure it works with `build` as well as `build_X`, make sure to also define a hook for the non-typed method, such as:

``` ruby
def link
  link_css
end
def assemble
  assemble_css
end
```

The hook-based architecture of WebBlocks should make this trivial to do once you get the hang of it.

**Comment by ebollens** [comment]
Note that I chose to define the search path separate from the adapter definition itself. This decision was made because one might actually put the search path definition within a file they include within Rakefile-config.rb, such as follows...

A `config.rb` file within the source directory for the external adapter:

``` ruby
require 'pathname'
WebBlocks.config[:src][:search][:adapter]['example'] = {
  :class => 'ExampleAdapter::Handler',
  :path => (Pathname.new(__FILE__).parent + "/handler.rb").to_s
}
```

Then, if the user checked this out into, for example, as a sibling of the WebBlocks directory, their `Rakefile-config.rb` might then look something like:

``` ruby
require 'rubygems'
require 'extensions/kernel' if defined?(require_relative).nil?

# Bring in the adapter from a relative and known location
require_relative '../example_adapter/config.rb'

# Include the adapter
WebBlocks.config[:src][:adapter] = 'example'
```
