### ISSUE TITLE
ARIA Integration

### ISSUE THREAD

**Issue by loganfranken** [ucla-oarc-web/WebBlocks#36]
We'll want to address integrating ARIA (http://www.w3.org/TR/wai-aria/) at some point. We could offer suggestions for where and how developers/designers should add ARIA roles, states, and properties to HTML but, I think, slightly more important, we'll want the JavaScript libraries to output the appropriate ARIA attributes (jQuery UI, for example, does a pretty comprehensive job with this).

I'm not sure if that's something that should occur during the prototyping stage or maybe later on as a pass over all of the entities when they are closer to the end of development. I would argue for the latter, but I would love to hear other input.

**Comment by ebollens** [comment]
We should probably do a pass-over in a few weeks when we've got a few more defined.

**Comment by ebollens** [comment]
@chris4ucla what do you think about ARIA? It's a bit outside of my competency, but I know it's a big win for accessibility.

**Comment by spiritcapsule** [comment]
Yes, agreed ARIA is a big win for accessibility. As we do evaluations, we often recommend adding ARIA landmarks to improve accessibility. In one or two examples we have found it overused. (Resulting in not-so-helpful clutter.) As long as they are used in a balanced way, they are definitely helpful. Let us know when you're ready for us to take a look.

**Comment by modernrockstar** [comment]
Patrick Burke (burke@ucla.edu) helped us test ARIA landmarks on the gateway. He's a great resource for anything accessibility.

**Comment by spiritcapsule** [comment]
Joseph, that's what I meant by we will take a look. Patrick is on my team.

**Comment by ebollens** [comment]
@chris4ucla I think we could use advice during the dev cycle (such as improving the prototypes to make sense if there are particular ones where ARIA fits in "all" cases). It's hard to do this as an afterthought or to have people without a lot of experience with ARIA guiding ARIA use and then getting audited post-implementation.

**Comment by spiritcapsule** [comment]
I agree that doing this as early in the dev cycle as possible is best. Is there some place where the MWF 2.0 is implemented where we can try some test cases. I'd really like to have Patrick take a look. That's going to be the best way to come up with suggestions.

**Comment by ebollens** [comment]
@chris4ucla the templates folder defines the entities we've got so far, and that's where all future entities go. Since we're under such early development, there isn't really a kitchen sink of examples yet.

**Comment by ebollens** [comment]
I've implemented an ARIA mapper here:
https://github.com/ebollens/jQuery.ariaMapper

This was integrated into WebBlocks in #452
