### ISSUE TITLE
support for Retina display resolution level images

### ISSUE THREAD

**Issue by albertwu** [ucla-oarc-web/WebBlocks#368]
This is a eventual feature request: if it isn't there already, there should be support for detecting retina display (i.e. very high dpi displays) so that sites can display images optimized for retina displays.

**Comment by jeffpignataro** [comment]
This is actually a relatively easy javascript function which is laid out here:
http://briancray.com/posts/detect-retina-displays-with-javascript

Simply - window.devicePixelRatio > 1;

Unfortunately, this does not detect the actual DPI for the screen but only if the person has a screen that supports more than 1 device-independent pixel (dip) per physical pixel.

**Comment by ebollens** [comment]
@jeffpignataro one of the problems with detecting retina displays through Javascript is that, by the time Javascript runs, most user agents will have already queued a set of assets for downloading, so substituting assets at that point creates a double load problem. To avoid this problem, the task has to be delegated to the server.

The trick we likely want to use here is something like what we did with the Device Telemetry Stack leveraged by MWF 1.2 and above, which uses a cookie-based mechanism to detect `devicePixelRatio` and then write a cookie for processing by the server. In the event that this cookie is set, a `.htaccess` file can be used to delegate to a server-side script the task of deciding which version of an image is loaded. A couple nasty caveats here: only works with Apache if we use `.htaccess` (other web servers may have comparable functionality) and the switching functionality will be dependent on some environment/language. In the event that no cookie is set (first page load), then we could fall back to letting Javascript replace the non-retina assets with retina assets.

**Comment by jeffpignataro** [comment]
That seems reasonable. I'd hoped that part of webBlocks philosophy was getting away from being dependent on a given web server type as MWF was (correct me if I'm wrong). But I completely agree that it is an awkward issue.

**Comment by ebollens** [comment]
We're doing our best to be server independent. The first version of WebBlocks does not include any server-side components. Unfortunately, when we hit scenarios like this, we may still be forced to. However, we will likely look at them as a separate project of sorts with its own repository so as not to appear to be implying that you need to be running on a particular platform to use the entirety of the toolkit.

**Comment by ebollens** [comment]
From the client-side, this has been resolved with the addition of polyfills for the `picture` element and `srcset` attribute; similarly, to support this functionality on the server-side, we include polyfills for HTTP Client Hints and Adaptive Images.

Documentation of these is in the 1.1 master, which I deployed to ebollens.github.io here:
- [picture Element](http://ebollens.github.io/WebBlocks/doc/#API/Package/picturefill)
- [srcset Attribute](http://ebollens.github.io/WebBlocks/doc/#API/Package/srcset)
- [HTTP Client Hints](http://ebollens.github.io/WebBlocks/doc/#API/Package/httpclienthints)
- [Adaptive Images](http://ebollens.github.io/WebBlocks/doc/#API/Package/adaptiveimages)
