### ISSUE TITLE
Entity/Blockquote Prototype

### ISSUE THREAD

**Issue by loganfranken** [ucla-oarc-web/WebBlocks#38]
Prototyping issue for Entity/Blockqoute

Dude, I thought this would be a easy one. Read more about attribution complexities:
https://github.com/ucla/WebBlocks/wiki/Entity-Blockquote

**Comment by ebollens** [comment]
I think as long as we support both `blockquote` and `figure.quote`, we'll be good.

**Comment by loganfranken** [comment]
Per our discussion today, I double-checked and the `blockquote` is definitely not supposed to contain the attribution:

"Content inside a blockquote must be quoted from another source" and "a quote to its attribution (which is not part of the quote and therefore doesn't belong inside the blockquote itself)" (http://www.whatwg.org/specs/web-apps/current-work/#the-blockquote-element).

So now we just need to decide if we want to support (the technically non-standard) Bootstrap's version:

```
<blockquote>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.</p>
    <small>Someone famous <cite title="Source Title">Source Title</cite></small>
</blockquote>
```

It looks funky at first, but this is an appropriate use of the `small` element (http://www.whatwg.org/specs/web-apps/current-work/#the-small-element) and also an appropriate use of the `cite` element since `cite` can only contain the title (http://www.whatwg.org/specs/web-apps/current-work/#the-cite-element). So, this is technically a non-standard approach, but since the attribution within a `blockquote` seems to be a pretty volatile area (see: http://html5doctor.com/blockquote-q-cite/), should we just go ahead and support it?

If there are no objections, I'll add an adaptation of the Bootstrap model as an alternate form to the prototype.

**Comment by ebollens** [comment]
@loganfranken I wouldn't oppose a format that supports `cite` inside a `blockquote` (because its used so commonly and is the most minimal approach - I'm amazed that it's not supported officially), but I wouldn't want to see a superfluous `small` tacked in there too. If you take a look at Foundation 3 (http://www.w3resource.com/zurb-foundation3/typography.php). It also places a `cite` inside `blockquote` but it does so without any extra markup. I'd be okay if this were supported.

**Comment by loganfranken** [comment]
@ebollens Bootstrap uses a containing `small` because `cite` technically can't contain a person's name ("A person's name is not the title of a work...and the element must therefore not be used to mark up people's names" http://www.whatwg.org/specs/web-apps/current-work/#the-cite-element). Thus, the Zurb Foundation's example would violate the spec.

This appears to be a pretty hot debate:
http://wiki.whatwg.org/wiki/Cite_element

So, we could support the following:

```
<blockquote>
    I'm sorry, Dave. I'm afraid I can't do that.
    <cite>HAL, 2001: A Space Odyssey</cite>
</blockquote>
```

As you said, this is really elegant and straightforward, but this would violate both (1) the `cite` within the `blockquote` rule and (2) the name of the person within `cite` rule.

I'm cool with supporting this markup, but I want to make sure that this fits with our overall planned policy regarding how closely the framework should follow the HTML5 spec.

**Comment by loganfranken** [comment]
Moved to development task (#67)
