### ISSUE TITLE
Entity/Table Prototype

### ISSUE THREAD

**Issue by loganfranken** [ucla-oarc-web/WebBlocks#43]
Still a lot of things to work out on this one:
https://github.com/ucla/WebBlocks/wiki/Entity-Table

**Comment by ebollens** [comment]
@loganfranken this looks good in my book. I was surprised by some of the rules related to tables (namely that `caption` must be `:first-child` and `tfoot` must come before `tbody`), but based on those, I think this format is clean. I'm going to close this ticket and I've opened #44 for development.

**Comment by loganfranken** [comment]
Updated wiki regarding `col` and `colgroup` commit:
https://github.com/ucla/WebBlocks/wiki/Entity-Table
