### ISSUE TITLE
Entity/Table Basic Styling

### ISSUE THREAD

**Issue by ebollens** [ucla-oarc-web/WebBlocks#44]
This ticket is for the development of `entity/table` as defined in #43.

**Comment by ebollens** [comment]
The base definitions are committed.

I spun off issue #46 to tackle the issue of scrollable.

Once the `caption` entity is styled (Bootstrap doesn't do this), then I can close this ticket.

**Comment by loganfranken** [comment]
Despite my misgivings (https://github.com/ucla/WebBlocks/wiki/Entity-Table), I think it may be useful to bring over the "condensed" CSS class as well. Any objections to that?

**Comment by loganfranken** [comment]
It looks like the order of `tfoot` before `tbody` is no longer required (see: https://github.com/ucla/WebBlocks/wiki/Entity-Table), so it may be appropriate to do some cross-browser testing to confirm the order that is more widely supported. I'll give it a shot.

**Comment by ebollens** [comment]
I have no issues with bringing across `.condensed`. I will go ahead and add it to the implementation. Can you update the prototype? Also, let's just leave `tfoot` in its current position. Although the requirement has been "lifted", we should assume that some browsers may still implement the old standard for it, and there's no reason we can't be "more strict" than the actual standard (I mean the standard itself actually makes quotes optional and doesn't require close tags in many places).

**Comment by ebollens** [comment]
I have added `.condensed` and removed `.scrollable` (given that we're splitting this into some other module per #46). In addition, I've modified the definition layout to be more extendable, and I've added `table > caption`. With the `caption` element, I've included support for a `.top` and `.bottom` class which will position the caption at the top or bottom of the table.

As such, I believe that this implementation is now complete. However, one difference from the design that Logan provided is that I don't text-align the `caption` to the right. I'll leave that issue outstanding for now while we consider it in #48. Closing this issue now as complete.

**Comment by loganfranken** [comment]
Updated wiki regarding `col` and `colgroup` commit:
https://github.com/ucla/WebBlocks/wiki/Entity-Table

**Comment by ebollens** [comment]
@loganfranken do you want to add `col[group]` to the `Entity/Table` implementation itself? I'm pretty unfamiliar with the construct.

**Comment by loganfranken** [comment]
@ebollens Will do

**Comment by loganfranken** [comment]
I added the highlighting (for `col`, `colgroup`, `tr`, `td`, and `th`). However, I'm not sure if I added it to the correct place? A couple questions:
1. Should I have added to the table entity definition? Or should the highlighting have been separated into a different entity?
2. Should the styling have been added to the base definition? Does it belong in the Bootstrap adapter?

**Comment by ebollens** [comment]
@loganfranken you're right to place this in the Bootstrap adapter because you're using things like `$infoBackground`, which is a variable from Bootstrap. However, it might make more sense to expose it through its own mixin because then it's evident to adapter writers that they need to accommodate this.

You would start this by creating another definition in the table core definition file of the form:

``` css
table {
    > tr, > tr > td, > tr > th, > colgroup, > colgroup > col {
        @include -entity-table-highlight;
    }
}
```

You'll note that I added the use of the _direct child selector_ because I don't want it leaking into unintended chid nodes deeper in the DOM.

Once you've done this, make sure to throw something in the core adapter as well, even if empty (probably right, since the styling you've applied is just the use of a Bootstrap variable and thus specific to the adapter), and then the implementation of the mixin using Bootstrap.

**Comment by loganfranken** [comment]
Awesome, thanks for your help, @ebollens; I'll implement those changes.

A couple discussion topics:
- I did a quick cross-browser check and it looks like the order of `tfoot` doesn't matter, so I think we're safe keeping the HTML4 standard, as you suggested
- Should we make a separate issue for discussing/researching responsive table approaches? Or is it too early?

**Comment by ebollens** [comment]
@loganfranken we can throw the issue up, but honestly I'd like to hold on this one for a bit, as we've got so much front and center to get done first :P

**Comment by ebollens** [comment]
@loganfranken accidentally deleted your awesome post by pressing the wrong button... but I was able to save it:

> Alright, I added in table hover and highlight styling.
> 
> A couple issues:
> 
> ##### Hover Styling
> 
> Twitter Bootstrap uses `table.table-hover` to apply the hover effect to the rows. I didn't like this at first, but then I realized it would probably be nice to have the option to toggle the row styling, so I implemented this as `table.hover`
> 
> ##### Mixin Scope
> 
> I defined the highlight entity as such (simplified for this example):

``` css
@mixin -entity-table {
    @extend .table;

    > tr, > tr > td {
        @include -entity-table-highlight;
    }
}

@mixin -entity-table-highlight {

    &.highlight {
        background: $infoBackground;
    }

}
```

> But I'm thinking it might be better to do the following:

``` css
@mixin -entity-table {
    @extend .table;

    > tr.highlight, > tr > td.highlight {
        @include -entity-table-highlight;
    }
}

@mixin -entity-table-highlight {

    background: $infoBackground;

}
```

> It makes the declaration a little messier, but I _think_ it might be necessary if, say, you need to apply override rules to the child of the target element. As an example, I almost needed this before I discovered `.table-hover` as I wanted to force a highlighted `td` to have the same color as the rest of the row:

``` css
@mixin -entity-table {
    @extend .table;

    /* Force the highlighted td to take on hover background color */
    > tr:hover > td.highlight {
        @include -entity-table-hover;
    }
}
```

> Although there may be an alternative solution I'm not considering (and I didn't actually need it in this case anyway).
> 
> Barring the above issues, this should be ready to close.

My comment to follow...

**Comment by ebollens** [comment]
I'd say we should probably tackle this with a new **core definition**:

``` css
table {
    > tr:hover > td.highlight {
        @include -entity-table-highlight;
    }
}
```

Then you can implement your Bootstrap adapter easily on top of it:

``` css
@mixin -entity-table-highlight {
    background: $infoBackground;
}
```

**Comment by loganfranken** [comment]
Hey @ebollens, I thought your comment implied that I should go with the second scoping option I presented, but I may have misunderstood. Let me know; otherwise, this should be ready to close.

**Comment by ebollens** [comment]
@loganfranken no, I don't think it should go in the `-entity-table` mixin at all. Instead, I think it should be a new definition in the core definitions and then it should have its own top-level mixin that gets implemented. Take a look again at my example above. The reason I say this is that it establishes the `.highlight` class as a WebBlocks core defined class, rather than something that is just implemented in some adapters.

**Comment by loganfranken** [comment]
Ahh, thanks for the explanation @ebollens: I think I'm starting to wrap my head around it. Does the most recent commit match with what you envisioned?

**Comment by ebollens** [comment]
Exactly.

**Comment by loganfranken** [comment]
Awesome; I'm closing this issue down.
