### ISSUE TITLE
picture Element

### ISSUE THREAD

**Issue by ebollens** [ucla-oarc-web/WebBlocks#448]
While #186 covers the ED of `img[srcset]`, jQuery Picture is popular because it is an approach similar to the `audio` and `video` tags. It could thus easily be provided as an alternate to the `img[srcset]` polyfill we should include by default.

**Comment by ebollens** [comment]
An update to this is that I just stumbled across a WD of the picture element:
http://www.w3.org/TR/html-picture-element

I'm thus classifying this as a Package: Polyfill rather than a Package: Functional; need to check and see how close this gets to what we've already got with jQuery Picture. We may have to implement something separate to support this.

**Comment by ebollens** [comment]
I've evaluated two slightly different approaches to this problem:
- picturefill - https://github.com/scottjehl/picturefill
- jQuery Picture - https://github.com/Abban/jQuery-Picture

At first, I much preferred Abban's solution because it uses the markup that's moving towards rec; however, it turns out that the use of the `source` tag is a serious problem in IE9. To quote Scott:

> IE9 (and 10 too I think) can't read the `source` elements because they're strictly outside of an expected `video` element context. Working around that requires a lot more JS logic and additional markup that'd be unnecessary to include for those using standard `span`s.

Given this, I'm going to package picturefill.

The syntax to use is:

``` html
<span data-picture data-alt="A giant stone face at The Bayon temple in Angkor Thom, Cambodia">
    <span data-src="external/imgs/small.jpg"></span>
    <span data-src="external/imgs/medium.jpg" data-media="(min-width: 400px)"></span>
    <span data-src="external/imgs/large.jpg" data-media="(min-width: 800px)"></span>
    <span data-src="external/imgs/extralarge.jpg" data-media="(min-width: 1000px)"></span>

    <noscript><img src="external/imgs/small.jpg" alt="A giant stone face at The Bayon temple in Angkor Thom, Cambodia"></noscript>
</span>
```

**Comment by ebollens** [comment]
I think that, by default, I'm going to include this polyfill but not the `img[srcset]` one. The reason for this is that this one is only 0.5 kb, whereas the `img[srcset]` one is 7 kb - and the syntax, by most people's review, is more exotic for the `img[srcset]` one. @loganfranken what do you think?

**Comment by loganfranken** [comment]
@ebollens I second `picturefill` as the default given the wider developer support for that approach, although `img[srcset]` seems to be catching some actual implementation fire at the moment. We may need to switch it up in the coming months, but this seems like the best default for now.
