### ISSUE TITLE
Entity/List

### ISSUE THREAD

**Issue by ebollens** [ucla-oarc-web/WebBlocks#45]
Develop the `entity/list` element as defined in #42.

**Comment by ebollens** [comment]
This is done. It was trivial, as Bootstrap actually directly applies these styles against `ul` and `ol` already. It's simply an empty definition in `adapter/bootstrap` as such. However, the definition is necessary as other frameworks may not use the `.unstyled` class and thus they will need to be ported to use the markup standard correctly.

**Comment by loganfranken** [comment]
Thanks @ebollens!

Updated the wiki to confirm implementation of "unstyled" CSS class:
https://github.com/ucla/WebBlocks/wiki/Entity-List
