### ISSUE TITLE
ARIA Attributes Polyfill

### ISSUE THREAD

**Issue by ebollens** [ucla-oarc-web/WebBlocks#452]
Not all UAs apply ARIA tags properly based on HTML 5 semantics.

We likely want something like this:
https://github.com/yatil/accessifyhtml5.js

Ideally though it should require less user-specific work - if nothing, maybe just a wrapper that intelligently selects where to place the ARIA attributes if not specifically defined.

**Comment by ebollens** [comment]
The link I provided at the start of this issue was good for inspiration, but it doesn't go far enough. We have all sorts of semantics in WebBlocks, many of which may not on their own end up being tagged up properly via ARIA. 

To start things off, let me offer the following invocation:

``` js
$(document).semanticsToAria();
```

As I see it, we should be marking major landmarks with `aria-role` such as `banner`, `contentinfo` and `main`. Seem hard to resolve? Well, if markup isn't semantic, it might be, but if it is, resolution should be as easy as:
- `banner` defaulting to the `header` element not contained within another sectioning element, if there is only one
- `contentinfo` defaulting to the `footer` element not contained within another sectioning element, if there is only one
- `main` defaulting to the `main` element not contained within another sectioning element, if there is only one

How do I mean?

Consider this example in HTML:

``` html
<body>
  <header><!-- site header --></header>
  <nav>
    <header><!-- nav header --></header>
  </nav>
  <main>
    <header><!-- page header --></header>
    <!-- page contents -->
    <footer><!-- page footer --></footer>
  </main>
  <footer><!-- site footer --></footer>
</body>
```

Under what I'm proposing, we'd automatically cast as:

``` html
<body>
  <header aria-role="banner"><!-- site header --></header>
  <nav>
    <header><!-- nav header --></header>
  </nav>
  <main aria-role="main">
    <header><!-- page header --></header>
    <!-- page contents -->
    <footer><!-- page footer --></footer>
  </main>
  <footer aria-role="contentinfo"><!-- site footer --></footer>
</body>
```

In cases where we already mark an `aria-role` for one of these three, we should not mark another, as the spec requires that no more than one is defined. Similarly, if we find more than one header or footer that aren't within a sectioning element (can't have more than one main per HTML 5 spec itself), then we don't want to place one as it's indeterminate.

However, suppose someone has done the following:

``` html
<body>
  <header><!-- non-banner header --></header>
  <header id="site-header"><!-- site header that should be banner --></header>
</body>
```

We should still be able to resolve this, although in this case, we just need to get a bit more explicit about resolution:

``` js
$(document).semanticsToAria({
    "roles": {
        "selectors": {
            "banner": "#site-header"
        }
    }
});
```

To avoid sandboxing ourselves in here, though, let's add another property that allows us to say to _not_ use the polyfill for the header:

``` js
$(document).semanticsToAria({
    "roles": {
        "selectors": {
            "banner": "#site-header"
        },
        "polyfills": {
            "exclusions": ["banner"]
        }
    }
});
```

This may not seem important for this example, but in other cases such as `article`, we may want to keep on using the polyfill while also defining our own additional selectors to mark as `article` - hence why the exclusion makes sense.

On the polyfill front, though, we should make it possible to disable all of the role polyfills if people don't want them:

``` js
$(document).semanticsToAria({
    "roles": {
        "polyfill": false
    }
});
```

Again, may seem a bit verbose in the options being passed, but I'd like to support things besides roles eventually - and as such, the polyfill disabler should be within roles, as we might also want to disable all polyfills, including for things besides row, such as:

``` js
$(document).semanticsToAria({
    "polyfill": false
});
```

Shifting gears slightly from this track and returning to the concept of WebBlocks semantics, consider this example we should also seek to cover:

``` html
<div class="message error">
  <h1>Authentication Failure</h1>
  <p>The username and password combination provided does not match a valid user.</p>
</div>
```

The `error` and `danger` connotations on a message are the sorts of things that should immediately draw the focus of a user. Consequently, an `aria-role="alert"` makes sense here. It should be as easy to add this as something like:

``` js
$(document).semanticsToAria({
    "roles": {
        "selectors": {
            "alert": [".message.error",".message.danger"]
        },
        "callbacks": {
            "alert": function(plugin){
                this.semanticsToAria.resolveLabeledBy();
            }
        }
    }
});
```

You'll note I've introduced a new `resolveLabeledBy()` method here under a `semanticsToAria` namespace. The idea of this is that, when we actually apply an `aria-role` of region (or any sub-class, including alert), the spec says we _should_ provide a `aria-labeledby` attribute. Since the element in question might not have an id to begin with, a bit more trickery is also needed to deal with this. The implementation of this function (assuming that call is used to set the element in question as the context, such as in the jQuery's .each function) is thus:

``` js
    function(labelSelectors){

        if(!labelSelectors)
            labelSelectors = headerElements

        ele = $(this.element)

        if(!ele.attr('aria-labeledby')){
            var children = $(labelSelectors).filter(function(){ return ele.find(this.toString()).length > 0 }).get()
            if(children.length > 0){
                var child = ele.find(children[0]).first()
                if(child.attr('id') === undefined)
                    child.attr('id', "aria-"+Math.random().toString(36).substring(2));
                ele.attr('aria-labeledby',child.attr('id'))
            }
        }

    }
```

While it isn't a big deal for this one, I can see other cases where you might want to apply the callback polyfill in addition to the callback you're explicitly settings, while in other cases you might only want to do your own callback. As such, the above example could be extended to invoke the "parent" callback, namely the one that handles the polyfill, such as:

``` js
$(document).semanticsToAria({
    "roles": {
        "selectors": {
            "alert": [".message.error",".message.danger"]
        },
        "callbacks": {
            "alert": function(plugin){
                this.super();
                this.semanticsToAria.resolveLabeledBy();
            }
        }
    }
});
```

As another example, consider the `nav.search` class (see (WebBlocks-kit-core:extension/blocks/nav/_search.scss)[https://github.com/ucla/WebBlocks-kit-core/blob/master/extension/blocks/nav/_search.scss] for the motivating case). In this particular example, we _don't_ want to use `aria-role="navigation"`, even though the `nav` element is the proper HTML 5 element to tackle the problem.

To get around this, we introduce a filter callback:

``` js
$(document).semanticsToAria({
    "roles": {
        "selectors": {
            "search": "nav.search"
        },
        "filters": {
            "navigation": function(){ return !$(this).hasClass('search') }
        }
    }
});
```

Putting it all together, what I'm essentially proposing is a library that has a set of default polyfills for ARIA roles it can assume by HTML semantics, with a clean and simple way for attaching semantics such as those established by WebBlocks. The final invocation might look something like this:

``` js
$(document).semanticsToAria({
    "polyfill": true,
    "roles": {
        "polyfills": {
            "exclusions": ["banner"]
        },
        "selectors": {
            "banner": "#site-header",
            "search": "nav.search",
            "alert": [".message.error",".message.danger"]
        },
        "filters": {
            "navigation": function(){ return !$(this).hasClass('search') }
        },
        "callbacks": {
            "alert": function(plugin){
                this.super();
                this.semanticsToAria.resolveLabeledBy();
            }
        }
    }
});
```

Finally, since code speaks louder than words, let me provide some code that implements exactly what I'm describing:

``` js
;(function ( $, window, document, undefined ) {

    var pluginName = 'semanticsToAria',
        sectionElements = ['article','section','nav','aside','h1','h2','h3','h4','h5','h6','header','footer','main'],
        headerElements = ['header','hgroup','h1','h2','h3','h4','h5','h6'],
        resolveLabeledBy = function(plugin){ this.semanticsToAria.resolveLabeledBy() },
        defaults = {
            "polyfill": true,
            "roles": {
                "polyfill":null,
                "polyfills": {
                    "selectors": {
                        "article": "article",
                        "banner": "header:not("+sectionElements.join(' header):not(')+" header)",
                        "complementary": "aside",
                        "contentinfo": "footer:not("+sectionElements.join(' footer):not(')+" footer)",
                        "main": "main",
                        "navigation": "nav",
                        "region": "section"
                    },
                    "callbacks": {
                        "article": resolveLabeledBy,
                        "region": resolveLabeledBy
                    },
                    "filters": {},
                    "exclusions": []
                },
                "selectors": {},
                "filters": {},
                "callbacks": {},
                "exclusions": []
            }
        };

    function Plugin( element, options ) {
        this.element = element;
        this.options = $.extend( true, {}, defaults, options);
        this._defaults = defaults;
        this._name = pluginName;
        this.init();
    }

    Plugin.prototype.init = function () {

        var plugin = this,
            element = this.element,
            options = this.options,
            onlyOnceWithRole = ['banner','contentinfo','main'],
            roles = {},
            selected,
            roleFilters = $.extend({}, options.roles.polyfills.filters, options.roles.filters)
            roleCallbacks = $.extend({}, options.roles.polyfills.callbacks, options.roles.callbacks);

        jQuery.each(options.roles.selectors, function(k, v){
            roles[k] = jQuery.isArray(v) ? v : [v] 
        });

        if(options.roles.polyfill || options.polyfill && options.roles.polyfill !== false){
            jQuery.each(options.roles.polyfills.selectors, function(k,v){ 
                if(options.roles.polyfills.exclusions.indexOf(k) < 0){
                    if(!roles[k]){
                        roles[k] = jQuery.isArray(v) ? v : [v]
                    }else{
                        jQuery.merge(roles[k], jQuery.isArray(v) ? v : [v]) 
                    }
                }
            });
        }

        jQuery.each(roles, function(name, selectors){

            if(options.roles.exclusions.indexOf(name) < 0){

                selected = $(element).find(selectors.join(', ')).filter(function(){ return $(this).attr('aria-role') === undefined })

                if(roleFilters[name])
                    selected = selected.filter(roleFilters[name])

                if(onlyOnceWithRole.indexOf(name) >= 0 && (selected.length + $(element).find('[aria-role="'+name+'"]').length > 1))
                    return;

                selected.attr('aria-role',name);

                if(roleCallbacks[name])
                    $('[aria-role="'+name+'"]').each(function(){
                        var ele = this;
                        ele.super = function(){
                            if(options.roles.polyfill || options.polyfill && options.roles.polyfill !== false)
                                if(options.roles.polyfills.callbacks[name] && options.roles.polyfills.exclusions.indexOf(name) < 0)
                                    options.roles.polyfills.callbacks[name].call(ele, plugin)
                        }
                        ele.semanticsToAria = new SemanticsToAriaHelper(ele);
                        roleCallbacks[name].call(ele, plugin)
                    })
            }
        })

    };

    var SemanticsToAriaHelper = function(element){
        this.element = element;
    }

    SemanticsToAriaHelper.prototype.resolveLabeledBy = function(labelSelectors){

        if(!labelSelectors)
            labelSelectors = headerElements

        ele = $(this.element)

        if(!ele.attr('aria-labeledby')){
            var children = $(labelSelectors).filter(function(){ return ele.find(this.toString()).length > 0 }).get()
            if(children.length > 0){
                var child = ele.find(children[0]).first()
                if(child.attr('id') === undefined)
                    child.attr('id', "aria-"+Math.random().toString(36).substring(2));
                ele.attr('aria-labeledby',child.attr('id'))
            }
        }

    }

    $.fn[pluginName] = function ( options ) {
        return this.each(function () {
            if (!$.data(document, 'plugin_' + pluginName)) {
                $.data(document, 'plugin_' + pluginName, 
                new Plugin( this, options ));
            }
        });
    }


})( jQuery, window, document );
```

As is obvious, this is quite it's own little library, so I will implement this into its own package and then load it into WebBlocks in the same way we do any other package.

Thoughts?

/CC @chris4ucla @loganfranken @lnicks @melcassio

**Comment by ebollens** [comment]
@hyperboy might also be interested in this discussion so tagging him as well

**Comment by ebollens** [comment]
I've gone ahead and set up a repo for this here:
https://github.com/ebollens/jQuery.ariaMapper

Hoping to get an initial version cranked out and integrated into WebBlocks this week (along of course with the other v1.1.01 tasks assigned to me).

**Comment by ebollens** [comment]
I've added a set of basic tests to the repo for all the polyfill libraries and the helper that resolves labeledBy on roles that, per the spec, should have an `aria-labeledby`.

**Comment by ebollens** [comment]
I've gone ahead and split the library up. Generically, it's `$.ariaMapper(options)` with a helper `$.ariaMapperHelper(operation, ..)`. This handles HTML semantics and user-defined cases passed through the options.

Extending this, I've also created a WebBlocks facade as `$.ariaWebBlocksMapper(options)` whereby, in addition to HTML 5, a set of WebBlocks semantics are also applied by default. This allows the user to pass in user-defined cases via this, if they want to build on WebBlocks semantics rather than the generic ones mentioned above.

To understand how the `$.ariaMapper(options)` works, the WebBlocks facade is actually a good place to start. It defines its default options passed to ariaMapper as:

``` js
{
    "roles": {
        "selectors": {
            "alert": [ 
                ".message.error", 
                ".message.danger", 
                ".message.important", 
                ".message.required" 
            ],
            "search": [ "nav.search" ],
            "status": [ 
                ".message.highlight", 
                ".message.success", 
                ".message.warning", 
                ".message.info" 
            ]
        },
        "filters": {
            "navigation": function(){ return !this.hasClass('search') }
        },
        "callbacks": {
        },
        "exclusions": []
    },
    "labeledby": {
        "selectors": {
            "form.form div.control label input": function(){
                var label = this.closest('div.control').children('label').first();
                if(label.find('input').length == 0)
                    this.ariaMapperHelper('setLabeledBy', label)
            }
        }
    }
}
```

The WebBlocks facade is available here:
https://github.com/ebollens/jQuery.ariaMapper/blob/master/jQuery.ariaWebBlocksMapper.js

The base implementation is available here:
https://github.com/ebollens/jQuery.ariaMapper/blob/master/jQuery.ariaMapper.js

Additionally, the helper is available here:
https://github.com/ebollens/jQuery.ariaMapper/blob/master/jQuery.ariaMapperHelper.js

And finally, a pretty full (although not totally complete) set of test cases are here:
https://github.com/ebollens/jQuery.ariaMapper/blob/master/test.js

I think this is ready for a preliminary integration into WebBlocks as an optional module. Once we establish enough confidence in it, this might be a good candidate to bump into a default since accessibility really should be encouraged.

@chris4ucla @loganfranken @lnicks @hyperboy what do you think?

**Comment by lnicks** [comment]
I'm digging it, at this point we can throw it in to any site, and it really shouldn't cause extra problems right?  That being said, I'd like to throw it into a site with some actual content.  We could duplicate senate (on d7ln) and take it for a test run.  I didn't use a ton of HTML5 in them, but in cases where it could be used, it should be simple to add.  It seems like the most real world of places?

**Comment by ebollens** [comment]
Yeah, that sounds good. Easiest way to do so since it's not in WebBlocks as a package yet would be to include the three script files in the `head`, and then at the end of the body, place the following:

``` js
$(document).ariaWebBlocksMapper();
```

This should invoke it to run all of its polyfill and WebBlocks rules.

**Comment by ebollens** [comment]
Just fixed my comment - ref should be `document`.

**Comment by ebollens** [comment]
As a note, the final way to invoke this, per pull request #505, is:

``` js
$('body').blocks().ariaMapper()
```
