### ISSUE TITLE
Mobile Click Delay Plugin

### ISSUE THREAD

**Issue by ebollens** [ucla-oarc-web/WebBlocks#453]
Mobile click events are belated by a 300ms delay. This leads to a lack of a responsive feel when working on mobile browsers, one of the big criticisms of responsive (and mobile web) sites. @trott did a cool plugin (https://github.com/ucsf-ckm/LightningTouch) but informed us later that he's moved over to using fastclick (https://github.com/ftlabs/fastclick). There are a minority of cases where the delay might be needed to detect a double-tap, but in most cases, this is the preferred behavior, so I think this should probably be a default.

**Comment by spiritcapsule** [comment]
When you turn on accessibility in iOS it changes the behavior of the clicks such that single click is used to identify something on screen and double click is used to activate it. So I'm wondering whether removing the delay has any affect on how the accessibility-enabled click events work. @ebollens or @trott can you point us at a url to test against?

cc// @pburkeucla @lnicks

**Comment by Trott** [comment]
@chris4ucla, I can not locate this feature on my iOS devices nor in Apple's documentation. I'm probably just not using the right terminology or something. Can you tell me where to find it/how to turn it on?

**Comment by lnicks** [comment]
Voiceover is the name of the feature you're looking for.

http://support.apple.com/kb/ht3598

I don't know how up to date this article is, but it's under general > settings > accessibility I believe.

**Comment by spiritcapsule** [comment]
on my iPad (i don't have an iPhone but I would assume it's similar), it's under Settings > General > scroll all the way to the bottom > Accessibility > VoiceOver > turn on.

**Comment by pburkeucla** [comment]
Yes, I think the way they hide Accessibility at 
the bottom of the 2nd screen under General is the 
biggest barrier to Voiceover usage...

Patrick

At 10:28 AM 9/17/2013, Chris Patterson wrote:

> on my iPad (i don't have an iPhone but I would 
> assume it's similar), it's under Settings > 
> General > scroll all the way to the bottom > 
> Accessibility > VoiceOver > turn on.
> 
> ­
> Reply to this email directly or 
> https://github.com/ucla/WebBlocks/issues/453#issuecomment-24606725view 
> it on GitHub.

## 

Patrick J. Burke

Coordinator
UCLA Disabilities &
Computing Program

Phone: 310 206-6004
E-mail: burke@ucla.edu
Location: 4909 Math Science

Department Contact: dcp@oit.ucla.edu

**Comment by Trott** [comment]
Cool. So m.ucsf.edu uses FastClick and it seems to work fine with Voiceover turned on. The UCSF app for iOS also uses FastClick (it's an HTML view under the hood) and it works fine with Voiceover too, at least based on my very superficial testing.

**Comment by spiritcapsule** [comment]
sounds good.
