### ISSUE TITLE
Entity/Table .scrollable

### ISSUE THREAD

**Issue by ebollens** [ucla-oarc-web/WebBlocks#46]
@loganfranken I'm unsure what exactly `.scrollable` does for `Entity/Table`. Any interest in describing it a bit further (features are empty in `README.md`) and then in implementing it? I've already committed the base shell for `Entity/Table` in #44.

**Comment by loganfranken** [comment]
Argh, forgot to reference the issue (explanation of `.scrollable` and updated prototype): 1b736a3cee515824999be6520398a3ead86449eb

I'm a little on the fence about including this in the base framework, so I was more or less putting the feelers out there to see if other people thought this was a good feature. (Or, more specifically, a good _core_ feature that shouldn't be implemented as a plug-in later)

However, if other people like it, I will definitely be game to implement it. I'll start implementing it either way as I'm adding this to a project I'm currently working on anyway.

**Comment by ebollens** [comment]
Since you're working on this for another project anyways, lets go ahead and include it. However, how about we add it as a different component so that one can choose to include it modularly or not? My thought is that we would put this in some area besides `entity`. Thoughts on what we might call it?

**Comment by loganfranken** [comment]
Sounds like a plan.

Not sure about the name as this is always called a "scrollable table with fixed headers" or something similarly generic. "Scrollable Table" sounds fine to me, although it's not very fun. Something like "Compact Table", "Table View", "Framed Table", or "Table Window" could also work.

**Comment by ebollens** [comment]
By name, I really mean namespace, as in some collection besides `entity` like `ui/table/scrollable` or something. I don't like `ui` but I'm using it as an example. The point is that I'd like someone to be able to include all of `entity` to get a baseline set and then be able to specify that they want certain pieces from other areas.

**Comment by loganfranken** [comment]
Ahh, gotcha. I might need a little more coffee first, but maybe a new root namespace `data` since this component is focused on displaying a large amount of data: `data/table/scrollable`?

**Comment by ebollens** [comment]
Might make sense, but my thought is that we want a namespace that encompasses all the cool extra things that you can include. So if I'm content to just run with a much larger instance, I just compile the whole thing in. The idea is like using jQuery UI on top of jQuery, at least how I'm thinking about it. We have `Entity`, which is like a baseline set, and then we will have a whole bunch of extra components. Some of them will go in an `Interactivity` namespace like the target-trigger engine (implemented for MWF first), while others aren't really about interaction, but rather about extending existing entities (and thus would go in some other namespace rather than `Entity` or `Interactivity`).

**Comment by loganfranken** [comment]
We probably just need to pick something that works and then change it later: `extend/table/scrollable` or `ext/table/scrollable`? `ui` could also work for right now.

**Comment by ebollens** [comment]
Hmmm, `Extend` is an interesting idea. Maybe we actually make it mirror the base ones, so you have something like `Extend/Entity/Table/Scrollable`?

**Comment by loganfranken** [comment]
@ebollens Sounds like a plan; I'll roll with that

**Comment by ebollens** [comment]
@loganfranken just so you know, I'm going with `extend` as the name of the namespace for these sorts of advanced features.

**Comment by loganfranken** [comment]
After finally getting a chance to explore this, I think we might actually want to drop it (at least for now).

There are a number of solutions to this problem:
- http://www.imaputz.com/cssStuff/bigFourVersion.html
- http://www.farinspace.com/jquery-scrollable-table-plugin/
- http://www.cssbakery.com/2010/12/css-scrolling-tables-with-fixed.html
- http://www.cssplay.co.uk/menu/tablescroll

All of them essentially accomplish this in the same way: set explicit widths on the `th` and `td` elements and then play around with the location of `thead` in the markup. For a responsive framework, explicit widths aren't really a viable solution. A possible solution is to use the explicit width solution but then set the width dynamically through JavaScript based on the fluid container.

This is still an option, I suppose, but it just seems like overkill for something that was just supposed to be an enhancement extension to the table entity and I feel it introduces a lot of complexity very early on for the table entity (really, I thought this was going to involve setting a height and overflow on `tbody` and calling it a day)

Unless anyone else disagrees, I'm just going to close this issue right now and refocus on the more core entities in my queue.
