### ISSUE TITLE
Text Alignment Classes

### ISSUE THREAD

**Issue by ebollens** [ucla-oarc-web/WebBlocks#48]
@atsengucla @ccheung @loganfranken what are your thoughts related to having text alignment classes like `.text-right`, `.text-center` and `.text-left`? A place where I'm thinking this would be useful is `table > caption`, for example, where you've got a full width caption. In Logan's image that he included, the caption is aligned right, but in other places, you might want it centered or aligned right.

**Comment by loganfranken** [comment]
I never love adding these types of non-semantic CSS class names, but I think they can be very useful for Web Blocks Users who would like to avoid writing little to no CSS, so I would vote to include them.

**Comment by ebollens** [comment]
While I agree they're not semantic, the problem is that they are a very common pattern. Although I wish I was just semantic everywhere, the fact of the matter is that I often find myself using these just to save time. If we add these, for example, we don't have to worry about how the user aligns their text because they're just base definitions.

We can place these in their own file, which would allow a particular compile of WebBlocks that neglects them.

**Comment by loganfranken** [comment]
+1 to everything you said, @ebollens 

I think they are fine in one the core files as they will be a useful base utility class. We'll be hitting this issue again with the float classes (e.g., `.right` and `.left`), clearfixing (e.g., `.cf` or `.clear`), image replacement (e.g., `.ir`), and the visibility classes (e.g., `.hidden` or `.invisible`), all of which I think should be included in a core part of the framework.

I'm just concerned that if we create a new file for every non-semantic set of CSS classes, things might get a little spread out and confusing. But, if that seems like too paranoid of a concern then I think the separate file sounds like a great idea.

**Comment by ebollens** [comment]
@loganfranken, a bit more on those (I know, we're deviating from the original point of the thread, but maybe the thread's purpose has changed a bit)...

I would want to see the float classes prefixed similar to above as `.float-left` and `.float-right`. Similarly, maybe we do `.float-clear`, as it's far more descriptive than `.clear`, even though many of us know what it means.

For visibility, `.hidden` works for me. It's useful sometimes when writing Javascript tools.

I'm unsure what image replacement is.

As for things getting spread out, I'm not too worried about that. If we end up with something like a `Base` namespace (I don't like this name though!), for example, we then have like a `Base/Type` subspace with `Base/Type/Align`. That's an easy place to put the text alignment. Similarly, we'd end up with something like `Base/Block/Float` and that stores the float classes. In almost all cases, a user will probably just include all of the `Base` (or whatever we call it) namespace, but they could choose to instead just include pieces of it if they don't want some of these.

**Comment by loganfranken** [comment]
@ebollens Nice, I think that's a good balance between customization/ease of "compiling" the framework.

Should we set up issues for each of these (float alignment, clearfixing, image replacement, and visibility)? Although float alignment may need to wait until the larger grid discussion.

Image replacement is a technique for replacing text with images so that you can have an image but maintain the semantics of a different element (I could explain more in-depth in a place somewhere dedicated to this topic). A common example is having `<h1>Website Title</h1>` swapped out with an image via CSS (see: http://css-tricks.com/css-image-replacement/). There's a lot of techniques for accomplishing this with pros/cons to each (and even some newer techniques discovered in the past year or so). HTML5 Boilerplate includes a class for this purpose : https://github.com/h5bp/html5-boilerplate/blob/master/css/main.css#L132

**Comment by ebollens** [comment]
@loganfranken I actually think, when it comes to float alignment, that we can just implement them straight. The thing with grids is that, by defining all the `Entity` elements with semantics, we've actually just avoided the question altogether - instead the grid becoming a backend implementation that's achieved using the `@include` for mixins to achieve spanning or `@extend` for classes like `.span` and `.row-fluid`. An example is in the Bootstrap adapter's baseline implementation of the menu bar. It's not a pretty implementation, but more done as an example. We need one of those nifty designer folks to come make it pretty - or at least I need to sit down and actually think about style a bit.

Yes, let's go ahead and set up issues for each.

We should definitely create an issue for image replacement. While the others are pretty cut and dry - and could probably just start with an implementation ticket, image replacement seems to have a lot of flavors we should think about.
