### ISSUE TITLE
Detect Existing Capabilities in HTTP Client-Hints Polfyfill

### ISSUE THREAD

**Issue by loganfranken** [ucla-oarc-web/WebBlocks#481]
During the call today, we discussed the possible need to extend the HTTP client-hints polyfill (#450) to detect if client-hints is already enabled, since [client-hints is now supported in the latest chromium builds](https://plus.google.com/+PaulIrish/posts/GvQ9vDEi4oh).

As @ebollens noted, it's probably too early for this to be a real concern and this will likely be added to the current HTTP client-hints polyfill. I figured I would still drop down an issue as a reminder.

**Comment by ebollens** [comment]
Javascript operates at the DOM level, where Client Hints operates at the HTTP level. For Javascript to gain access to support info, it would have to be pushed by the browser into the DOM. Currently, it does not appear this is happening, and the spec doesn't call for it. Consequently, I am closing this as _cannot resolve_.
