### ISSUE TITLE
Responsive Table: Scroll Overflow

### ISSUE THREAD

**Issue by loganfranken** [ucla-oarc-web/WebBlocks#482]
Implement a solution that wraps a table in a container that scrolls on overflow as a basic responsive table approach.

**Comment by ebollens** [comment]
I've decided to go ahead and implement this one in time for the beta, while the other two will be left open for future work.

**Comment by ebollens** [comment]
The implementation here is four part:
1. Adds a new `.scrollable-collapse` modifier that may be set on `.table` elements in the `Entity/Table` namespace
2. Adds a new `.overflow-scroll` class as the first class in a new `Base/Block/Overflow` namespace
3. Adds a new Javascript wrapper `$.fn.blocks().overflowScrollable()` in `Base/Block/Overflow` 
4. Adds an onload initialization in `Entity/Table/Collapse/Scrollable` to invoke `$.fn.blocks().overflowScrollable()`

Most basic markup prototype is thus:

``` html
<table class="table scrollable-collapse">
    <!-- Content wider than table container -->
</table>
```

If a `.scrollable-collapse` is added after the load event, then the initializer can be called to get scrollable effect:

``` js
$('.table.scrollable-collapse').blocks().overflowScrollable('init');
```

Alternatively, post-load objects may be added to DOM as follows for scrollable overflow:

``` html
<div class="overflow-scroll">
    <table class="table scrollable-collapse">
        <!-- Content wider than table container -->
    </table>
</div>
```
