### ISSUE TITLE
Required Form Support

### ISSUE THREAD

**Issue by ebollens** [ucla-oarc-web/WebBlocks#487]
HTML 5 provides us with the `required` attribute on inputs; however, I'm unconvinced that this is the best approach for us. It has a couple problems:
- Only some browsers support and polyfills, while reasonable, don't mimic completely
- Cannot add DOM elements that appear when validation passes or fails
- Must use programmatic controls to do fancy things

I thus propose adding a new `data-required` attribute to the `div.control` structure:

``` html
    <div class="control" data-required="true">

        <label for="test">Label</label>
        <input type="text" id="test">

    </div>
```

This may look equivalent to putting `require` on the input, but let me get a bit fancier:

``` html
    <div class="control" data-required="true">

        <label for="test">Label</label>
        <input type="text" id="test">
        <span class="required-fail">This field is required</span>
        <span class="required-pass">This field has validated properly</span>

    </div>
```

Now we need to start introducing Javascript to make this happen. Sure, we could use the require attribute and do this, but then we end up in this weird mis-mash case between how browsers that support `require` alert (especially the aria portion of it) and how the polyfills do. 

Going a bit further, let me pose this:

``` html
<form class="form">

    <div class="form-required-fail message required">
        The form field "Label" must be specified.
    </div>

    <div class="control" data-required="true">

        <label for="test">Label</label>
        <input type="text" id="test">
        <span class="required-fail">This field is required</span>
        <span class="required-pass text-success">This field has validated properly</span>

    </div>

    <div class="control">
        <input type="submit" class="button">
    </div>

</form>
```

The behavior I'd like to see:
- For any div.control under form.form with data-required="true":
  - The class required is added to the div.control
- Whenever an input, select or textarea under data-required="true" is changed:
  - If all inputs in div.control are filled, required is removed from control
  - Otherwise, required is added to the control and role="alert" is fired
- If data-required="true" has required class on it:
  - Any .required-fail is visible
  - Any .required-pass is hidden
- If data-required="true" does not have required on it:
  - Any .required-pass is visible
  - Any .required-fail is hidden
- When one tries to submit, if any required controls empty, the form won't submit; instead:
  - Any .form-required-fail elements become visible and role="alert" is fired

I think this is clear and describable through semantics.

As usual, the talk without code is merely supposition, so here's the code that speaks to this:
- https://github.com/ucla/WebBlocks-kit-core/blob/master/extension/blocks/form/_required.js
- https://github.com/ucla/WebBlocks-kit-core/blob/master/extension/blocks/form/_required.scss

Note that this relies on #486.

/CC @loganfranken

**Comment by loganfranken** [comment]
The proposed solution looks good to me from a technical standpoint and I think you have a good case for `data-required` here.

I'm a little concerned about the transition from `data-required` to `required` when that attribute becomes more widely supported (since WebBlocks is a forward-looking toolkit), but I can't really offer a better solution given the constraints on the validation form API and the current cross-browser implementation inconsistencies.

**Comment by ebollens** [comment]
I see `required` as different than `data-required`. Semantically, `required` imposes the constraint upon _the form element_, whereas `data-required` imposes the constraint upon _the control_. 

By imposing it on the control, we can allow a user to set up content that only shows up when it's passing or failing the required constraint, as well as content that shows up within the DOM if validation fails when you try to submit. Sure, we could sniff `required` and polyfill it, but I'm actually not a fan of that here: I think that exceeds the behavior of the attribute, as suggested by the browser.

**Comment by loganfranken** [comment]
@ebollens That seems reasonable to me.

**Comment by ebollens** [comment]
Attaching the handler will work as:

``` js
$(window).load(function(){
    $('form.form').blocks().requiredFormControls('init');
});
```

When adding new forms with Javascript, need to invoke this upon them if after `load` event.

Additionally, validation can be handled at other times such as:

``` js
$('form.form').blocks().requiredFormControls('validate')
```

This will return a set of all forms that _do_ validate.

This means you can detect if forms didn't validate as:

``` js
$('#your-form').blocks().requiredFormControls('validate').length > 0
```

Note that this call will automatically show a `.form-required-failure` element if it exists.
