### ISSUE TITLE
Cluster Structure Element

### ISSUE THREAD

**Issue by ebollens** [ucla-oarc-web/WebBlocks#492]
A number of design patterns rely on a set of equal-spaced elements. This could come in the form of icons, quick links, article thumbnails, etc. While the `row` structure can accommodate this, it has several deficits:
- Does not support _five_ elements
- Can collapse 4-2-1, but not 6-3-2-1

Based on this fact, I'm proposing a new Base/Structure/Cluster element.

The markup format will be incredibly simple (between two and six direct children):

``` html
<div class="cluster">
    <div>1</div>
    <div>2</div>
    <div>3</div>
    <div>4</div>
    <div>5</div>
    <div>6</div>
</div>
```

In all cases, the direct children will be blocks and equal-spaced items. The collapse behaviors:
- `1 x 6` -> `2 x 3` - > `3 x 2` -> `6 x 1`
- `1 x 5` -> `1 x 3 + 1 x 2` -> `2 x 2 + 1 x 1` -> `5 x 1`
- `1 x 4` -> `2 x 2` -> `4 x 1`
- `1 x 3` - > `3 x 1`
- `1 x 2` - > `2 x 1`

To give an example, check out the first bit of this page:
http://ucla.github.io/WebBlocks-kit/_examples/pattern_grids.html
(resize the page to see the changes at different breakpoints)

@loganfranken @chris4ucla @lnicks et al., thoughts?

**Comment by spiritcapsule** [comment]
I like the fact that when a group of 5 items collapses to two rows, the items are centered so that 4/5 center rather than aligning left. However, I can see a case where one would want them to align left rather than center. Can we have left-alignment be optional, defaulting to centered?

**Comment by ebollens** [comment]
Certainly.

**Comment by lnicks** [comment]
This will be immensely helpful, we have encountered this already several times.  Would it be possible to create sets of classes that enable this only at certain breakpoints, like the `hide-above-xxxx` or such?

Also, how does styling effect these? are we assuming that the blocks are styled individually or lumped together? do they collapse within a prestyled block, or do we rely on individual block design and just create rows of those?

**Comment by ebollens** [comment]
> Would it be possible to create sets of classes that enable this only at certain breakpoints, like the hide-above-xxxx or such?

I don't believe so. It would be too complex and bloat CSS immeasurably. However, we could define a couple allowed levels of behavior maybe.

> Also, how does styling effect these? are we assuming that the blocks are styled individually or lumped together? do they collapse within a prestyled block, or do we rely on individual block design and just create rows of those?

Positioning is achieved via the same mechanisms as with `.row` and `.panel-X`.

**Comment by lnicks** [comment]
I'm actually thinking more along the lines of stylistic elements such as borders or elements, in particular lists, which is where we encounter this the most.  We have had issues with separators between objects, that when collapsed behave oddly.

**Comment by ebollens** [comment]
> I'm actually thinking more along the lines of stylistic elements such as borders or elements, in particular lists, which is where we encounter this the most. We have had issues with separators between objects, that when collapsed behave oddly.

Up until the day you guys let me say "IE7 can appear 150% broken", we're stuck with the fact that borders have to be applied to inner elements and cannot be applied on `div.cluster` or its direct children `div.cluster > *`.

**Comment by ebollens** [comment]
Actually, I take that back. It won't happen until you let it be 150% broken for IE 8 and below. Thank you Microsoft for only partially fixing the box model in IE 8.

**Comment by loganfranken** [comment]
This looks good to me, @ebollens!
