### ISSUE TITLE
Base/Block

### ISSUE THREAD

**Issue by ebollens** [ucla-oarc-web/WebBlocks#54]
I can think of at least three modules that could go here:
- float
- positioning
- visibility

This stems off of a discussion in #48.

**Comment by ebollens** [comment]
@atsengucla @ccheung @loganfranken what are your thoughts between the class `float-container` or `float-wrapper` for an element that wraps floats (a "clearfix" as it is often called). I don't like the term "clearfix" because, while that's technically what it is, in reality we're talking about a div that contains/wraps floats in their entirety.

I'm also struggling to pin down the difference between `overflow:auto` and a clearfix. Bootstrap uses a clearfix in 15 different places and only uses `overflow:auto` in 4 places, yet they seem to do roughly the same thing.

**Comment by ghost** [comment]
@ebollens overflow:auto is a much simpler solution if you don't care about the visibility of items that overflow. http://stackoverflow.com/questions/2373544/clearfix-vs-overflow

[EDIT by @ebollens: Fixed tag of self as it was misspelled]

**Comment by ebollens** [comment]
@ladyheatherly where does the visibility issue actually crop up? I know it exists with `overflow:hidden` but I haven't been able to come up with a case that demonstrates it for `overflow:auto`. There's got to be a reason that the CSS gurus at Twitter chose to use the clearfix instead.

**Comment by ghost** [comment]
@ebolens overflow:auto visibility is only an issue if you want to

avoid scrollbars on containers with text that overflows (due to a container's height declaration)
apply a negative margin or negative x/y positioning to a contained element (to intentionally overflow it)

I believe overflow:hidden and overflow:auto behave the same, except the latter will add scrollbars for overflow content whereas the former will just hide it.

Both properties will also ignore the adjacent margins of the first and last contained elements. This is difficult to explain in a way that makes sense... just play around with this little test page I made.

**Comment by ebollens** [comment]
The margin point makes sense. As for the other bit, does that mean there's no negative to just using `overflow:auto|hidden` when you're talking about `div` elements?

**Comment by loganfranken** [comment]
Wow, I'm glad we're having this discussion as I did not realize the `overflow` clearfix was this versatile (I've always just relied on existing clearfixes).

Here's a fiddle demonstrating one of the issues @ladyheatherly describes (specifically an element being forced to flow outside its container):
http://jsfiddle.net/vUEtL/

**Comment by loganfranken** [comment]
Also, as to the naming: I think you make a good point (that `float-container` is really more accurate to the element's purpose). I'm all for using a different name; however, the only major concern would be whether or not straying from convention may confuse Users of the framework (as they will expect `clear-fix` or something similar).

**Comment by ebollens** [comment]
Well, what might make sense is actually to provide the following:
- `.float-container` implemented with `overflow: auto`
- `.clearfix`that just provides the clearfix
- `.float-container.clearfix` replaces `overflow: auto` instead with a clearfix

This approach has several advantages:
- A semantic name for the float container that uses the really simple `overflow: auto` (hence my naming argument above) and will work in the vast majority of cases
- When the `overflow: auto` doesn't work for `.float-container`, then just append the additional class `.clearfix` and it will drop the `overflow:auto` and use the clearfix instead.
- The ability to apply use `.clearfix` standalone as you are right that its a pretty familiar pattern

It might not seem important to have a `.float-container.clearfix`, but my thought is that, if people become accustomed to putting their floats within a `.float-container`, then appending another class (or maybe just a suffix such as a class like `.float-container-cf`) is more intuitive because it still describes what the element's purpose is. Of course, one could forego this `.float-container` element, given that `.clearfix` and `.float-container.clearfix` are the same, but the point is simply that the definition of `overflow:auto` should be `.float-container:not(.clearfix)` (unless of course we go with a suffix-based class name instead, which I'd also be okay with).

Thoughts?

**Comment by ampodobas** [comment]
I would argue that `.float-container` without  `.clearfix` is the most readily understandable (from first glance) and intuitive naming convention. Appending a hyphenated qualifier to class names for further differentiation is a great approach moving forward as it's easier to write quickly

**Comment by loganfranken** [comment]
Is the thought behind preserving `overflow: auto` to help out the browser's layout engine by providing an option with fewer rules? Or are there other advantages to preserving both techniques?

Since the clearfix will already be coming along for the ride (thus, not increasing the CSS file size), I think it might just be easier to have the developers/designers use the same clearfix option every time (rather than having two types). I think having both options might require more novice designers to have too much of an understanding of the behind-the-scenes.

**Comment by ebollens** [comment]
@loganfranken the problem is that the space complexity of `@extend .clearfix;` is 4x what it is for `@extend .float-container;`. That's because the actual implementation of the clearfix manifests as:

``` css
.clearfix{*zoom:1}
.clearfix:before,.clearfix:after{display:table;content:""}
.clearfix:after{clear:both}
```

For `.sample-container` to extend it, you end up with:

``` css
.clearfix,.sample-container{*zoom:1}
.clearfix:before,.clearfix:after,.sample-container:before,.sample-container:after{display:table;content:""}
.clearfix:after,.sample-container:after{clear:both}
```

Contrast that with this:

``` css
.float-container{overflow:auto}
```

When you `@extend .float-container`, you just end up with:

``` css
.float-container,.sample-container{overflow:auto}
```

So the point is that using clearfix for `@extends` (or _even worse_ reapplying the mixin `@include clearfix()` from Bootstrap) adds a significant amount of additional space when used numerous times. That's my primary motivator for providing both. In the majority of cases, we would want to push the user to `.float-container`. Suppose they run into the overflow issues however so they need the clearfix-variant. Then they would just add the clearfix class so it would be `.float-container.clearfix` or else maybe they append so they use `.float-container-cf`. I don't know which I like more, but either would work from my book. Of course, they could also just use `.clearfix`, but appending is sometimes easier than replacing, and it is far more legible when reading the code if everything carries the same expected class name plus modifiers, rather than the other way around. Exposing `.clearfix` directly (not even a choice if using the Bootstrap adapter) is also good though for those that are more comfortable with the pattern.

**Comment by ghost** [comment]
The downside to overflow:auto on the UCLA template is that it will crop the offset left- and right-column images on pages like http://www.ucla.edu/admissions/affordability. These are pretty common on the site.

The <div class="section"> has the .clearfix class instead, so the image is not cropped and extends beyond it's ancestor container.

**Comment by ebollens** [comment]
@ladyheatherly would it be too much though to just use either `.float-container.clearfix`, `.float-container-cf` or just `.clearfix`? Among the former two, which makes more sense, a second class or a suffix?

**Comment by ebollens** [comment]
Note that Bootstrap goes with `.hide` for the `display:none` class, while Boilerplate uses `.hidden`. Foudation 3 doesn't use either, but it prefers the "hide" adjective. Which should we go with? @loganfranken initially suggested `.hidden`, but given that the verb seems more prevalent, I'm inclined to go that way. There's also the pseudo class `:hidden`, so using `.hide` disambiguates some (although `.hide` will be selectable as `:hidden` as well :P). Thoughts?

Also, what do people think about providing some position classes like `block-left`, `block-center` and `block-right`? I'm not sure if they're useful enough to add as an option, because using `margin: auto` with explicit widths is only helpful if explicit widths are set, and we're not likely to have them set as such without the user going into the CSS anyways, which defeats the purpose of making them utility classes. At the moment, I'm thinking keep it simple and thus a NO on these.

**Comment by loganfranken** [comment]
@ebollens  Ahh, I wasn't thinking from the mixin perspective. Alright, you convinced me.

Personally, I like both the clarity of the suffix (as you mention) and the simple --> advanced feel of adding the suffix. So I would vote for `.float-container` and `.float-container-cf`. (With `.clearfix` as an available option as well). We might also want to consider `.float-container-adv`, `.float-container-ext`, or `.float-container-full` as alternative suffixes to fit the alternate naming trend?

**Comment by loganfranken** [comment]
@ebollens I don't really have a super strong opinion either way (re: `.hide` vs `.hidden`); what matters most is sticking with convention, I think. In this case, the convention is almost verb for utility classes (e.g. `.float-right`), so `.hide` sounds good.

I think we should leave the `block-` positioning out for the reasons you state.

**Comment by ebollens** [comment]
Any concerns with not providing a `.show`? My thought is that, if you don't want to hide it, you just remove `.hide`. The reason is that `.show` would have to be implemented for some particular `display` property, and I don't think there's any _one_ property that captures this.

As for suffix naming, I'd be opposed to using something like `-adv`, `-ext` or `-full` because that's a bit deceptive and doesn't leave room for other potential "improvements" we might provide as options to the container.

**Comment by loganfranken** [comment]
No, I'm with you on not providing `.show`.

**Comment by ebollens** [comment]
For visibility, not actually putting it in `Base/Block` but instead:
- `Base/Visibility/Hide` for the basic `.hide` class
- `Base/Visibility/Responsive` for the responsive classes (like Bootstrap has them)

**Comment by ebollens** [comment]
For now, I've added the following classes for responsive visibility:
- `.show-small`
- `.show-medium`
- `.show-large`
- `.hide-small`
- `.hide-medium`
- `.hide-large`

I've also added two variables that can be set in your `_variables.scss` file:
- `$base-breakpoint-small`
- `$base-breakpoint-medium`

These are of the `min-width` variant, meaning that you set them to `768px` and `978px` as opposed to using `max-width` variants that would be one px smaller.

**Comment by ebollens** [comment]
It's also worth note that I did not attach the Bootstrap adapter to these. The reason is that, given how Bootstrap is implemented, the logic goes the wrong way. With variables, we want to set the Bootstrap equivalent variable and then extend Bootstrap. Unfortunately, here we would need to propagate the Bootstrap value into our variable's value and then use that one, but that goes against the idea of having a configuration interface of WebBlocks variables and adds in adapter-specific ones that would be required to set the WebBlocks one.

**Comment by ebollens** [comment]
I'm closing this ticket now as we've completed the `Base` entities I set out to do here.
