### ISSUE TITLE
Entity/Blockquote

### ISSUE THREAD

**Issue by loganfranken** [ucla-oarc-web/WebBlocks#67]
Development task for `entity/blockquote` (prototype issue: #38)

Note that the use of `cite` within Form 1 of the prototype is not correct per the HTML5 specification (although it matches the Zurb Foundation style). At the end of the day, it's really up to the designer/developer as to whether or not they want to closely follow the spec; my only concern is to what degree we should feel responsible for ensuring that people are using the _correct_ markup when they might not know otherwise.

**Comment by loganfranken** [comment]
This is pretty much finished (barring review), but there are a couple issues I need to tackle:

### Right Alignment

I need to integrate Bootstrap's right-aligned blockquote. Bootstrap floats the blockquote to the right (as well as right-aligns the text), but I don't know if that is entirely necessary. Right-aligning the text should be sufficient (and wouldn't bring along float side effects).

Should I just tack on a `.right` modifier CSS class? It's not very semantic, but it's straightforward. Piggybacking on `.float-right` would be a little more economical CSS-wise, but I feel like it doesn't accurately describe our goal here.

### Callout Width

The "callout" style is supposed to have a smaller width. I wasn't sure if this should be set by tacking on a grid utility class to the entity itself?

### Responsive Callout

The callout will need to flip over to a 100% width element at a certain viewport. I wasn't sure if I should wait to handle this after we have had the breakpoint discussion?

**Comment by ebollens** [comment]
If you're just trying to provide a left-aligned block quote, is there any reason you can't just use the `.text-right` class that's already in WebBlocks? If that's fine, then simply skip this completely.

I think callout is a broader theme than just blockquote, so we should probably tackle it separately. The point you raise about responsive gets right at that fact. Let's hit it separately.

**Comment by loganfranken** [comment]
@ebollens That all sounds good to me!

Updated the prototype/template to reference `.text-right` since I want to explicitly show how we handle Bootstrap's use cases. Closing this and moving the remaining callout discussion into a new issue
