### ISSUE TITLE
Grunt Not Included In Package.json

### ISSUE THREAD

**Issue by loganfranken** [ucla-oarc-web/WebBlocks#69]
Unless I'm misunderstanding, `config.rb` seems to imply that `grunt` will be available in the nearby `node_modules` directory, but it's not listed as a dependency in `packages.json`.

**Comment by ebollens** [comment]
Actually, `config.rb` implies that, if it's a node module, then it's available for execution via the route it specifies. Based on the mechanics of `npm install`, this means relative to the `packages.json` file that loads it. You will note that `/packages.json` doesn't have it as a requisite, while `/package/jquery/packages.json` does. This is intentional: WebBlocks does not need Grunt, but jQuery does.

**Comment by loganfranken** [comment]
Oh, durp, that makes total sense, thanks @ebollens. I was getting this confused with another issue I was encountering where Windows seems to choke on the relative path shell commands; let me double-check that's not just something I'm misunderstanding, though.

**Comment by ebollens** [comment]
I haven't tested the relative pathing portion on Windows, so if it is misbehaving, that's the alternative?

**Comment by loganfranken** [comment]
Hey @ebollens, the relative pathing ended up working just fine, but I did need to add `node` in front of the relative paths:

```
WebBlocks.config[:exec][:grunt]      = 'node ./node_modules/grunt/bin/grunt'
WebBlocks.config[:exec][:uglifycss]  = 'node ./node_modules/uglifycss/uglifycss'
WebBlocks.config[:exec][:uglifyjs]   = 'node ./node_modules/uglify-js/bin/uglifyjs'
```

**Comment by loganfranken** [comment]
I set up Web Blocks on another Windows machine and I again had to add the `node` prefix in the `config` to avoid a 127 error ("command not found"):

```
WebBlocks.config[:exec][:grunt]      = 'node ./node_modules/grunt/bin/grunt'
WebBlocks.config[:exec][:uglifycss]  = 'node ./node_modules/uglifycss/uglifycss'
WebBlocks.config[:exec][:uglifyjs]   = 'node ./node_modules/uglify-js/bin/uglifyjs'
```

This makes sense as Windows will ignore the Unix shebang at the top (`#! /usr/bin/env node`) and so it has no idea what to do with the file. I'm not sure of the best way to handle this for compatibility across both systems?

**Comment by ebollens** [comment]
Assigning this to myself to do.
