### ISSUE TITLE
Entity/Nav/Bar

### ISSUE THREAD

**Issue by loganfranken** [ucla-oarc-web/WebBlocks#70]
Development task for `entity/nav/bar` (prototype issue: #9)

**Comment by alicetseng** [comment]
met with @ebollens today and given our ramp-up with getting familiar with SASS we decided that the best way we could help with trimming down the implementation backlog was for me to help with CSS prototypes; feel free to punt me what you need help with in terms of all the nav entities and I can produce html/css mockups that you can abstract into SASS mixins. I'll commit them as implementation.html and implementation.css in the template files.

**Comment by alicetseng** [comment]
Looks like there are 2 tasks open for this issue. An open ticket #31. I think it's open - anyway just posted a question RE this for @loganfranken and @ebollens there.

**Comment by loganfranken** [comment]
Ahh, you're right, @atsengucla: thanks for catching that. I'm going to close this issue.
