### ISSUE TITLE
Responsive Tables

### ISSUE THREAD

**Issue by loganfranken** [ucla-oarc-web/WebBlocks#71]
We will need to research and choose the best option(s) for implementing responsive tables (or, alternatively, make the decision not to support them in the framework).

As @ebollens notes in #44, this is an issue we should wait to discuss since there is a lot of other work that could be done at the moment (prototyping, basic designs, etc.).

**Comment by loganfranken** [comment]
Created a wiki page for this research:
https://github.com/ucla/WebBlocks/wiki/Research:-Responsive-Tables

**Comment by ebollens** [comment]
Nice summary! My thoughts are now in the wiki.

**Comment by loganfranken** [comment]
Whoops, sorry @ebollens, I should have marked that it was a work-in-progress. I think the list is finished now (although it's more or less just [Chris Coyier's awesome round-up](http://css-tricks.com/responsive-data-table-roundup/) with some extra examples and implementation details). Your suggestions still hold true, though; notable additions you might want to check out are the second "Pinned Column" example (flipped table) and the new "Hide Columns" category.

Moving this into the next milestone although I imagine we'll be circling in on an implementation choice soon.

**Comment by loganfranken** [comment]
Added some additional thoughts on the wiki:
https://github.com/ucla/WebBlocks/wiki/Research:-Responsive-Tables

@ebollens @atsengucla @ccheung 

Maybe we could settle on an implementation approach during tomorrow's discussion?

**Comment by loganfranken** [comment]
Moving to 0.1.05

**Comment by ebollens** [comment]
Agreed on settling on an implementation approach during tomorrow's meeting.

**Comment by loganfranken** [comment]
Based on today's meeting, we will implement this entity as follows:
- Build with standard table markup
- Provide Linearized Table option as extension
- Provide Scrollable Table option (w/ option for pinning table header) as extension

Hiding Columns option (w/ menu for re-enabling hidden columns) will be tabled ( _har har_ ) for now. This was a research ticket, so I'm going to close it and open tickets for the actual entity development.

**Comment by loganfranken** [comment]
Added information about a relatively new responsive table concept ("FooTable"): https://github.com/ucla/WebBlocks/wiki/Research:-Responsive-Tables Probably not something we'll consider first-pass, but it's an interesting concept nonetheless
