### ISSUE TITLE
Support for Cloning Submodules Over HTTP/HTTPS

### ISSUE THREAD

**Issue by loganfranken** [ucla-oarc-web/WebBlocks#76]
I think we discussed this at the workshop on Friday?

I was getting the Web Blocks build set up on a different computer and `git submodule update` kept failing with the error `fatal: read error: Invalid argument`

I eventually discovered it was a firewall issue; I went through and changed the submodule configurations to target `https://` instead of `git://` and the process went smoothly.

I'm not sure if it would be possible to either create a (1) configuration option or (2) at least some troubleshooting documentation to address this problem?

**Comment by ebollens** [comment]
Based on the discussion during last Friday's workshop, I agree that we should use `https` rather than `git` for this. I will make the necessary changes. Assigning to myself to do.

**Comment by ebollens** [comment]
For the time being, my change for this will simply modify the `.gitmodules` file. To use the new paths, you must delete existing packages (`rm -rf package/*`). A bit more long-term, as part of the custom builders, I'm also going to be retrofitting the whole way this stuff works.

**Comment by loganfranken** [comment]
Blargh, I'm not sure if there's much we can do here, but jQuery complicates matters by having `git://` submodules. So, when running a fresh `rake`, I had to go back in and change those still. This then seemed to cause the build to hiccup while trying to find a compiled version of jquery in a `dist` directory; I ran `grunt` manually to get things running again.

**Comment by ebollens** [comment]
Hmmm, that's a problem, and I don't think we can get around it. jQuery's submodules are its own submodules. Of course, if you're not compiling jQuery as a package, then it isn't a problem. If you are, though, oh well, then you need to have support for the `git://` protocol.
