### ISSUE TITLE
Clean Up Git Submodule Packages (After Failed Cloning)

### ISSUE THREAD

**Issue by loganfranken** [ucla-oarc-web/WebBlocks#77]
While I was stumbling around and investigating #76, git submodule cloning kept failing, leaving the clone in a unfinished state. So, when a clone fails, you first get the _real_ error, and then on subsequent attempts you get this error:

```
fatal: Needed a single revision
Unable to find current revision in submodule path 'package/jquery'
```

You can fix this by deleting the `.git` file in the `package/module` directory for the module in question. Since the error is so vague, I was wondering if it might be useful to document the steps to resolving this error in a "troubleshooting" section?

I'm not sure if this could be automated: it seems like a tell-tale sign that a clone did not go correctly is a package directory containing only a `.git` file (and no other files)

I had thought the `packages_clean` would wipe out the packages, but it didn't seem to have that effect for me (maybe I was doing something wrong?).

**Comment by ebollens** [comment]
Assigning this to myself to do.

**Comment by ebollens** [comment]
This is accomplished with a new `rake` directive (introduced in #78):

```
rake reset_packages
```

This will delete all package submodule check outs, requiring you to fetch them all again.
